### ISSUE TITLE
hydroshare container exits after running tests

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1057]
@pkdash, @hyi, @selimnairb 

Have noticed that the hydroshare container exits when the `coverage run manage.py test` call is made which is causing our Jenkin's job to report a failed state.

The error I've found in the `hydroshare.log` is this:

```bash
[15/Mar/2016 16:13:33] DEBUG [hs_core.hydroshare.resource:336] Copying uploaded file from /tmp/tmpywolGK/test.zip to /shared_temp
[15/Mar/2016 16:13:33] DEBUG [hs_core.hydroshare.resource:339] Retained upload as /shared_temp/test.zip
[15/Mar/2016 16:13:33] DEBUG [hs_core.hydroshare.utils:474] Opening /tmp/tmp2RPhqf/hs_core/tests/data/cea.tif as File with name hs_core/tests/data/cea.tif
[15/Mar/2016 16:13:33] DEBUG [django:105] Adding file hs_core/tests/data/cea.tif to resource a580f816cda443db96a973184a4c0044
[15/Mar/2016 16:13:34] DEBUG [hs_core.hydroshare.utils:474] Opening /tmp/tmp2RPhqf/tmp/tmpywolGK/text.txt as File with name tmp/tmpywolGK/text.txt
[15/Mar/2016 16:13:34] DEBUG [django:105] Adding file tmp/tmpywolGK/text.txt to resource a580f816cda443db96a973184a4c0044
[15/Mar/2016 16:14:55] ERROR [hs_tools_resource.utils:23] [WebApp] 'http://www.google.com/?resid=${HS_RES_ID}&restype=${HS_RES_TYPE}&mypara=${HS_UNDEFINED_TERM}&user=${HS_USR_NAME}' cannot be parsed by term_dict {'HS_RES_TYPE': 'GenericResource', 'HS_USR_NAME': 'scrawley', 'HS_RES_ID': 'b6cc2fceb92749feb02a7a4385dab88b'}.
Traceback (most recent call last):
  File "/home/docker/hydroshare/hs_tools_resource/utils.py", line 21, in parse_app_url_template
    new_url_string = Template(new_url_string).substitute(merged_term_dic)
  File "/usr/lib/python2.7/string.py", line 172, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib/python2.7/string.py", line 162, in convert
    val = mapping[named]
KeyError: 'HS_UNDEFINED_TERM'
```

The error also identifies @shawncrawley, which makes me wonder about the construct of what is failing if it's looking for a specific user (**scrawley** in this case) by name...

Ideas?

**Comment by hyi** [comment]
@mjstealey I am bringing @zhiyuli in since the error was raised from hs_tools_resource/utils.py and may be related to the new url mapping @zhiyuli implemented and got merged in recently.

**Comment by zhiyuli** [comment]
@mjstealey 
This is our testing code: https://github.com/hydroshare/hydroshare/blob/develop/hs_tools_resource/tests/test_web_app.py#L214

We raise this exception on purpose by providing a unknown term "mypara=${HS_UNDEFINED_TERM}", the following function catches this exception and logs it. 
https://github.com/hydroshare/hydroshare/blob/b6ef96b9e16395d9bac03ef526c70c457b0c5298/hs_tools_resource/utils.py#L23

**Comment by zhiyuli** [comment]
@mjstealey I dont think hydroshare container exits was caused by this testing code.....

**Comment by mjstealey** [comment]
> I dont think hydroshare container exits was caused by this testing code

I'll try a different approach and run the tests individually by app name and report back with the outcome. Something is causing the container to exit when tests are run, and it's been difficult to discern exactly what it is. The error I pasted above is the only one I could find in the log files which is why it appears.

**Comment by mjstealey** [comment]
Running app tests individually by using `coverage run manage.py test APP_NAME --keepdb`

Results:
- django_docker_processes  - ran 0 tests with no exit
- django_irods  - ran 0 tests with no exit
- ga_ows  - ran 0 tests with no exit
- ga_resources  - ran 51 tests with no exit (errors=48, failures=2)
- hs_access_control - ran 119 tests with no exit
- hs_app_netCDF  - ran 0 tests with no exit
- hs_app_timeseries - ran 9 tests with no exit
- hs_core - ran 107 tests and then **EXIT**
   
 ```
[2016-03-15 17:44:43 +0000] [32] [INFO] Worker exiting (pid: 32)
[2016-03-15 17:44:43 +0000] [28] [INFO] Worker exiting (pid: 28)
[2016-03-15 17:44:43 +0000] [31] [INFO] Worker exiting (pid: 31)
[2016-03-15 17:44:43 +0000] [1] [INFO] Shutting down: Master
[2016-03-15 17:44:43 +0000] [1] [INFO] Reason: Worker failed to boot.
```
- hs_docker_base  - ran 0 tests with no exit
- hs_geo_raster_resource - ran 0 tests with no exit
- hs_geographic_feature_resource - ran 7 tests with no exit
- hs_labels - ran 14 tests with no exit
- hs_metrics - ran 0 tests with no exit
- hs_model_program  - ran 0 tests with no exit
- hs_modelinstance  - ran 7 tests with no exit
- hs_rhessys_inst_resource - ran 0 tests with no exit
- hs_rhessys_modelinstance - ran 0 tests with no exit
- hs_script_resource - ran 2 tests with no exit
- hs_sitemap - ran 0 tests with no exit
- hs_swat_modelinstance  - ran 0 tests with no exit
- hs_tools_resource - ran 3 tests with no exit
- irods_browser_app - ran 0 tests with no exit
- ref_ts  - ran 0 tests with no exit
- theme  - ran 1 tests with no exit

The majority of the apps ran 0 tests and did not effect the running of the container. The only test that caused the container to exit was **hs_core**. Unsure why this is the case...

This should be replicable locally by executing `coverage run manage.py test hs_core` from the hydroshare container.

---

Log file information prior to container exiting

django.log

```bash
[15/Mar/2016 18:15:03] DEBUG [django:105] Adding file hs_core/tests/data/cea.tif to resource e75790ea9c7f47a6ba6a80439170d843
[15/Mar/2016 18:15:03] DEBUG [django:105] Adding file tmp/tmpjy4Ciz/text.txt to resource e75790ea9c7f47a6ba6a80439170d843
[15/Mar/2016 18:15:09] DEBUG [django:105] Adding file hs_core/tests/data/cea.tif to resource 4bedf4f96d0a4aefb27343e20f9310af
[15/Mar/2016 18:15:10] DEBUG [django:105] Adding file tmp/tmpZzTNKR/text.txt to resource 4bedf4f96d0a4aefb27343e20f9310af
[15/Mar/2016 18:15:16] DEBUG [django:105] Adding file hs_core/tests/data/cea.tif to resource 3e5a6956745742f3906c3ee1c98243ee
[15/Mar/2016 18:15:17] DEBUG [django:105] Adding file tmp/tmpEoabAd/text.txt to resource 3e5a6956745742f3906c3ee1c98243ee
[15/Mar/2016 18:16:06] DEBUG [django:105] Adding file hs_core/tests/data/cea.tif to resource 76d9c6c0b41d487b8aed5a23d8472939
[15/Mar/2016 18:16:07] DEBUG [django:105] Adding file tmp/tmphbe7r2/text.txt to resource 76d9c6c0b41d487b8aed5a23d8472939
```

gunicorn.log

```bash
[2016-03-15 18:16:16 +0000] [32] [INFO] Worker exiting (pid: 32)
[2016-03-15 18:16:16 +0000] [26] [INFO] Worker exiting (pid: 26)
[2016-03-15 18:16:16 +0000] [29] [INFO] Worker exiting (pid: 29)
[2016-03-15 18:16:16 +0000] [1] [INFO] Shutting down: Master
[2016-03-15 18:16:16 +0000] [1] [INFO] Reason: Worker failed to boot.
```

hydroshare.log

```bash
[15/Mar/2016 18:15:03] DEBUG [hs_core.hydroshare.resource:336] Copying uploaded file from /tmp/tmpjy4Ciz/test.zip to /shared_temp
[15/Mar/2016 18:15:03] DEBUG [hs_core.hydroshare.resource:339] Retained upload as /shared_temp/test.zip
[15/Mar/2016 18:15:03] DEBUG [hs_core.hydroshare.utils:474] Opening /tmp/tmpmKBLrN/hs_core/tests/data/cea.tif as File with name hs_core/tests/data/cea.tif
[15/Mar/2016 18:15:03] DEBUG [django:105] Adding file hs_core/tests/data/cea.tif to resource e75790ea9c7f47a6ba6a80439170d843
[15/Mar/2016 18:15:03] DEBUG [hs_core.hydroshare.utils:474] Opening /tmp/tmpmKBLrN/tmp/tmpjy4Ciz/text.txt as File with name tmp/tmpjy4Ciz/text.txt
[15/Mar/2016 18:15:03] DEBUG [django:105] Adding file tmp/tmpjy4Ciz/text.txt to resource e75790ea9c7f47a6ba6a80439170d843
[15/Mar/2016 18:15:09] DEBUG [hs_core.hydroshare.resource:336] Copying uploaded file from /tmp/tmpZzTNKR/test.zip to /shared_temp
[15/Mar/2016 18:15:09] DEBUG [hs_core.hydroshare.resource:339] Retained upload as /shared_temp/test.zip
[15/Mar/2016 18:15:09] DEBUG [hs_core.hydroshare.utils:474] Opening /tmp/tmpfAnCY5/hs_core/tests/data/cea.tif as File with name hs_core/tests/data/cea.tif
[15/Mar/2016 18:15:09] DEBUG [django:105] Adding file hs_core/tests/data/cea.tif to resource 4bedf4f96d0a4aefb27343e20f9310af
[15/Mar/2016 18:15:10] DEBUG [hs_core.hydroshare.utils:474] Opening /tmp/tmpfAnCY5/tmp/tmpZzTNKR/text.txt as File with name tmp/tmpZzTNKR/text.txt
[15/Mar/2016 18:15:10] DEBUG [django:105] Adding file tmp/tmpZzTNKR/text.txt to resource 4bedf4f96d0a4aefb27343e20f9310af
[15/Mar/2016 18:15:16] DEBUG [hs_core.hydroshare.resource:336] Copying uploaded file from /tmp/tmpEoabAd/test.zip to /shared_temp
[15/Mar/2016 18:15:16] DEBUG [hs_core.hydroshare.resource:339] Retained upload as /shared_temp/test.zip
[15/Mar/2016 18:15:16] DEBUG [hs_core.hydroshare.utils:474] Opening /tmp/tmpVqqk2A/hs_core/tests/data/cea.tif as File with name hs_core/tests/data/cea.tif
[15/Mar/2016 18:15:16] DEBUG [django:105] Adding file hs_core/tests/data/cea.tif to resource 3e5a6956745742f3906c3ee1c98243ee
[15/Mar/2016 18:15:17] DEBUG [hs_core.hydroshare.utils:474] Opening /tmp/tmpVqqk2A/tmp/tmpEoabAd/text.txt as File with name tmp/tmpEoabAd/text.txt
[15/Mar/2016 18:15:17] DEBUG [django:105] Adding file tmp/tmpEoabAd/text.txt to resource 3e5a6956745742f3906c3ee1c98243ee
[15/Mar/2016 18:15:36] DEBUG [oauthlib.oauth2.rfc6749.endpoints.resource:74] Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x7f55fe2bfc10>.
[15/Mar/2016 18:15:48] WARNING [py.warnings:1474] /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Date.start_date received a naive datetime (2014-08-10 00:00:00) while time zone support is active.
  RuntimeWarning)

[15/Mar/2016 18:15:48] WARNING [py.warnings:1474] /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Date.start_date received a naive datetime (2014-09-10 00:00:00) while time zone support is active.
  RuntimeWarning)

[15/Mar/2016 18:15:48] WARNING [py.warnings:1474] /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Date.start_date received a naive datetime (2011-08-10 00:00:00) while time zone support is active.
  RuntimeWarning)

[15/Mar/2016 18:15:48] WARNING [py.warnings:1474] /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Date.end_date received a naive datetime (2012-08-11 00:00:00) while time zone support is active.
  RuntimeWarning)

[15/Mar/2016 18:15:48] WARNING [py.warnings:1474] /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Date.start_date received a naive datetime (2011-08-11 00:00:00) while time zone support is active.
  RuntimeWarning)

[15/Mar/2016 18:15:48] WARNING [py.warnings:1474] /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Date.start_date received a naive datetime (2011-08-09 00:00:00) while time zone support is active.
  RuntimeWarning)

[15/Mar/2016 18:16:03] WARNING [py.warnings:1474] /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Date.start_date received a naive datetime (2016-01-20 00:00:00) while time zone support is active.
  RuntimeWarning)

[15/Mar/2016 18:16:03] WARNING [py.warnings:1474] /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Date.end_date received a naive datetime (2016-02-20 00:00:00) while time zone support is active.
  RuntimeWarning)

[15/Mar/2016 18:16:06] DEBUG [hs_core.hydroshare.resource:336] Copying uploaded file from /tmp/tmphbe7r2/test.zip to /shared_temp
[15/Mar/2016 18:16:06] DEBUG [hs_core.hydroshare.resource:339] Retained upload as /shared_temp/test.zip
[15/Mar/2016 18:16:06] DEBUG [hs_core.hydroshare.utils:474] Opening /tmp/tmp2rdLxt/hs_core/tests/data/cea.tif as File with name hs_core/tests/data/cea.tif
[15/Mar/2016 18:16:06] DEBUG [django:105] Adding file hs_core/tests/data/cea.tif to resource 76d9c6c0b41d487b8aed5a23d8472939
[15/Mar/2016 18:16:07] DEBUG [hs_core.hydroshare.utils:474] Opening /tmp/tmp2rdLxt/tmp/tmphbe7r2/text.txt as File with name tmp/tmphbe7r2/text.txt
[15/Mar/2016 18:16:07] DEBUG [django:105] Adding file tmp/tmphbe7r2/text.txt to resource 76d9c6c0b41d487b8aed5a23d8472939
```

error.log / access.log / system.log - nothing

**Comment by zhiyuli** [comment]
@mjstealey i have a question about the command to run testing code. 
I am using 
docker exec -ti hydroshare ./run-tests   --> run all testing code and show report
docker exec -ti hydroshare python manage.py test hs_geographic_feature_resource.tests.test_geo_feature  --> run individual testing code

am I doing it correctly? I never used "coverage run manage.py test APP_NAME..."

**Comment by mjstealey** [comment]
> docker exec -ti hydroshare ./run-tests

That call points to this file: https://github.com/hydroshare/hydroshare/blob/develop/run-tests#L1-L6

For testing purposes, I only issued the first line of that file manually from within the running hydroshare container. 
- If everything ran as expected I would be left in the container and ready to execute the next command.
- If something failed I would be dropped from the container as it died and not be able to execute the next command.

The only call that constantly drops me from the running container is `coverage run manage.py test hs_core`

You could see the same result from the VM using `docker exec hydroshare coverage run manage.py test hs_core` as well.

If the container is killed, it can be brought back up using `docker-compose start hydroshare`, and appears to run normally afterwards.

**Comment by mjstealey** [comment]
@zhiyuli - You're running tests just fine. We have a couple of scripts that wrap up some reporting in the output for local use or on Jenkins, but they are same calls you are using.

> hs_geographic_feature_resource.tests.test_geo_feature --> run individual testing code

I may have to run down the list of 100+ tests in hs_core like this to figure out which test(s) are causing the container to exit.

**Comment by zhiyuli** [comment]
@mjstealey got it thanks

**Comment by mjstealey** [comment]
@selimnairb - Would you mind looking into the test that causes the container to exit?

Tests run from hs_core that cause the container to exit:

- hs_core.tests.api.rest.test_create_resource.py

All tests run:
- python manage.py test hs_core.tests.api.native.test_add_resource_files.py
- python manage.py test hs_core.tests.api.native.test_bagit.py
- python manage.py test hs_core.tests.api.native.test_comment_on_resource.py
- python manage.py test hs_core.tests.api.native.test_core_metadata.py
- python manage.py test hs_core.tests.api.native.test_create_account.py
- python manage.py test hs_core.tests.api.native.test_create_new_version_resource.py
- python manage.py test hs_core.tests.api.native.test_create_resource.py
- python manage.py test hs_core.tests.api.native.test_delete_resource.py
- python manage.py test hs_core.tests.api.native.test_delete_resource_file.py
- python manage.py test hs_core.tests.api.native.test_endorse_comment.py
- python manage.py test hs_core.tests.api.native.test_endorse_resource.py
- python manage.py test hs_core.tests.api.native.test_get_capabilities.py
- python manage.py test hs_core.tests.api.native.test_get_checksum.py
- python manage.py test hs_core.tests.api.native.test_get_comments.py
- python manage.py test hs_core.tests.api.native.test_get_endorsement.py
- python manage.py test hs_core.tests.api.native.test_get_resource.py
- python manage.py test hs_core.tests.api.native.test_get_resource_by_shortkey.py
- python manage.py test hs_core.tests.api.native.test_get_resource_file.py
- python manage.py test hs_core.tests.api.native.test_get_resource_types.py
- python manage.py test hs_core.tests.api.native.test_get_revisions.py
- python manage.py test hs_core.tests.api.native.test_group_from_id.py
- python manage.py test hs_core.tests.api.native.test_list_group_members.py
- python manage.py test hs_core.tests.api.native.test_publish_resource.py
- python manage.py test hs_core.tests.api.native.test_resolve_doi.py
- python manage.py test hs_core.tests.api.native.test_set_access_rules.py
- python manage.py test hs_core.tests.api.native.test_set_group_owner.py
- python manage.py test hs_core.tests.api.native.test_set_resource_owner.py
- python manage.py test hs_core.tests.api.native.test_update_account.py
- python manage.py test hs_core.tests.api.native.test_update_group.py
- python manage.py test hs_core.tests.api.native.test_update_metadata.py
- python manage.py test hs_core.tests.api.native.test_update_resource.py
- python manage.py test hs_core.tests.api.native.test_update_resource_file.py
- python manage.py test hs_core.tests.api.native.test_user_from_id.py
- python manage.py test hs_core.tests.api.native.test_users.py
- python manage.py test hs_core.tests.api.native.test_utils.py
- python manage.py test hs_core.tests.api.rest.base.py
- python manage.py test hs_core.tests.api.rest.test_create_resource.py
- python manage.py test hs_core.tests.api.rest.test_resource_file.py
- python manage.py test hs_core.tests.api.rest.test_resource_list.py
- python manage.py test hs_core.tests.api.rest.test_resource_meta.py
- python manage.py test hs_core.tests.api.rest.test_resource_types.py
- python manage.py test hs_core.tests.api.rest.test_set_access_rules.py
- python manage.py test hs_core.tests.api.rest.test_user_info.py
- python manage.py test hs_core.tests.api.utils.py
- python manage.py test hs_core.tests.api.views.test_authorize.py
- python manage.py test hs_core.tests.runner.py
- python manage.py test hs_core.tests.serialization.test_generic_resource_meta.py

**Comment by selimnairb** [comment]
@mjstealey I'm working on another project.  I can look at this tonight or tomorrow.

**Comment by selimnairb** [comment]
@mjstealey As develop stands now (521985549efc825d32a90af5a20aad6f81d01e79) the hydroshare container fails to build because gunicorn is not installed by hs_docker_base or in the hydroshare Dockerfile.

**Comment by selimnairb** [comment]
@mjstealey Here are the results from my environment:

```
python manage.py test hs_core.tests.api.rest.test_create_resource.py
/usr/local/lib/python2.7/dist-packages/mezzanine/utils/conf.py:55: UserWarning: TIME_ZONE setting is not set, using closest match: Etc/UTC
  warn("TIME_ZONE setting is not set, using closest match: %s" % tz)
/usr/local/lib/python2.7/dist-packages/django/contrib/contenttypes/models.py:159: RemovedInDjango19Warning: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ContentType(models.Model):

/usr/local/lib/python2.7/dist-packages/autocomplete_light/widgets.py:19: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  from django.forms.util import flatatt

/usr/local/lib/python2.7/dist-packages/autocomplete_light/fields.py:8: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import GenericForeignKey

/usr/local/lib/python2.7/dist-packages/crispy_forms/utils.py:25: RemovedInDjango19Warning: memoize wrapper is deprecated and will be removed in Django 1.9. Use django.utils.lru_cache instead.
  default_field_template = memoize(default_field_template, {}, 1)

nosetests hs_core.tests.api.rest.test_create_resource.py --verbosity=1
Creating test database for alias 'default'...
.
----------------------------------------------------------------------
Ran 1 test in 16.371s

OK
Destroying test database for alias 'default'...
```

**Comment by mjstealey** [comment]
> because gunicorn is not installed by hs_docker_base

There seems to be an issue with docker grabbing the updated hs_docker_base:1.6.8 image

From your environment, do the following.
`$ docker pull mjstealey/hs_docker_base:1.6.8`

Then try to deploy again.

**Comment by selimnairb** [comment]
I just installed it via my Dockerfile, which leads to the above success.  Do you want me to test anything else?

**Comment by mjstealey** [comment]
The issue is caused by this [line](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/tests/api/rest/test_create_resource.py#L35)

```python
response = self.getResourceBag(res_id)
```

[getResourceBag](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/tests/api/rest/base.py#L40-L62) is defined as:

```python
    def getResourceBag(self, res_id):
        """Get resource bag from iRODS, following redirects
        :param res_id: ID of resource whose bag should be fetched
        :return: Django test client response object
        """
        bag_url = "/hsapi/resource/{res_id}".format(res_id=res_id)
        response = self.client.get(bag_url)

        self.assertEqual(response.status_code, status.HTTP_301_MOVED_PERMANENTLY)
        self.assertTrue('Location' in response)
        redir_url1 = response['Location'].replace('testserver', self.hostname)

        redir_response = self.client.get(redir_url1)
        self.assertEqual(redir_response.status_code, status.HTTP_302_FOUND)
        redir_url2 = response['Location'].replace('testserver', self.hostname)
        redir_response2 = self.client.get(redir_url2)

        bag_irods_url = redir_response2['Location'].replace('example.com', self.hostname)
        bag_response = self.client.get(bag_irods_url)
        self.assertEqual(bag_response.status_code, status.HTTP_200_OK)

        return bag_response
```

If the above line is commented out, all tests will run and the container will remain running upon completion. Expectedly, there are failed tests due to the line being commented out.

Uncommenting the line again will allow the tests to run and pass, but the container immediately exits upon completion.

**Comment by hyi** [comment]
@mjstealey Can you confirm whether this issue has been fixed by the PR #1078 and if so, close this issue?

**Comment by mjstealey** [comment]
Issue resolved, closing

**Comment by mjstealey** [comment]
fixed
