### ISSUE TITLE
hs_core - api rest tests - failing tests after hs_docker_base refactor

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1069]
While refactoring the hs_docker_base to use Python 2.7.11 two existing tests began failing. (see below)

```bash
======================================================================
FAIL: test_post_resource_get_sysmeta (hs_core.tests.api.rest.test_create_resource.TestCreateResource)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/docker/hydroshare/hs_core/tests/api/rest/test_create_resource.py", line 32, in test_post_resource_get_sysmeta
    self.assertEqual(content['resource_title'], title)
AssertionError: u'Untitled resource' != 'My Test resource'
-------------------- >> begin captured logging << --------------------
shapely.geos: DEBUG: Trying `CDLL(libgeos_c.so.1)`
shapely.geos: DEBUG: Library path: 'libgeos_c.so.1'
shapely.geos: DEBUG: DLL: <CDLL 'libgeos_c.so.1', handle 1680a00 at 7f3a6e559a50>
shapely.geos: DEBUG: Trying `CDLL(libc.so.6)`
shapely.geos: DEBUG: Library path: 'libc.so.6'
shapely.geos: DEBUG: DLL: <CDLL 'libc.so.6', handle 7f3a94d50000 at 7f3a6e559890>
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_create_resource_file (hs_core.tests.api.rest.test_resource_file.TestResourceFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/docker/hydroshare/hs_core/tests/api/rest/test_resource_file.py", line 79, in test_create_resource_file
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)
AssertionError: 400 != 201
-------------------- >> begin captured logging << --------------------
hs_core.hydroshare.resource: DEBUG: Copying uploaded file from /tmp/tmptJAstk/test.zip to /shared_temp
hs_core.hydroshare.resource: DEBUG: Retained upload as /shared_temp/test.zip
hs_core.hydroshare.utils: DEBUG: Opening /tmp/tmp_iZITQ/hs_core/tests/data/cea.tif as File with name hs_core/tests/data/cea.tif
django: DEBUG: Adding file hs_core/tests/data/cea.tif to resource 954ee5e1daad443a814b8f1e71232aec
hs_core.hydroshare.utils: DEBUG: Opening /tmp/tmp_iZITQ/tmp/tmptJAstk/text.txt as File with name tmp/tmptJAstk/text.txt
django: DEBUG: Adding file tmp/tmptJAstk/text.txt to resource 954ee5e1daad443a814b8f1e71232aec
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 298 tests in 318.813s

FAILED (failures=2)
```

**Comment by selimnairb** [comment]
test_create_resource.py is failing because of this [bug](https://github.com/tomchristie/django-rest-framework/issues/3951) in django-rest-framework.  Working on a work around.

**Comment by mjstealey** [comment]
completed
