### ISSUE TITLE
hs.getResourceFileList() OAuth 2 error

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#1096]
@selimnairb I am getting a `InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https` error that stems from `for resource in hs.getResourceList(types=types):` (see the Traceback below). The funny thing is, if I do not authenticate my instance of the HydroShare object at all (i.e. `hs = HydroShare()`) it works fine. Also, the OAuth version is working fine on other hs_restclient calls, such as `hs.getSystemMetadata(res_id)`. Do you know what's going on here?

I already tried passing `use_https=True` to the `HydroShare()` instantiation, just to be sure. Still no change.

```shell
[Thu Mar 31 22:11:03 2016] [error] Traceback (most recent call last):
[Thu Mar 31 22:11:03 2016] [error]   File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Thu Mar 31 22:11:03 2016] [error]     response = self.process_exception_by_middleware(e, request)
[Thu Mar 31 22:11:03 2016] [error]   File "/usr/lib/tethys/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Thu Mar 31 22:11:03 2016] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Mar 31 22:11:03 2016] [error]   File "/usr/lib/tethys/src/tethys_apps/tethysapp/hydroshare_gis/controllers.py", line 228, in get_hs_res_list
[Thu Mar 31 22:11:03 2016] [error]     for resource in hs.getResourceList():
[Thu Mar 31 22:11:03 2016] [error]   File "/usr/lib/tethys/lib/python2.7/site-packages/hs_restclient/__init__.py", line 262, in _getResultsListGenerator
[Thu Mar 31 22:11:03 2016] [error]     r = self._request('GET', res['next'], params=params)
[Thu Mar 31 22:11:03 2016] [error]   File "/usr/lib/tethys/lib/python2.7/site-packages/hs_restclient/__init__.py", line 208, in _request
[Thu Mar 31 22:11:03 2016] [error]     verify=self.verify)
[Thu Mar 31 22:11:03 2016] [error]   File "/usr/lib/tethys/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 310, in request
[Thu Mar 31 22:11:03 2016] [error]     raise InsecureTransportError()
[Thu Mar 31 22:11:03 2016] [error] InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
```

**Comment by selimnairb** [comment]
@shawncrawley Can you supply a minimal example that triggers the error (omitting of course any client IDs or secrets)?  Thanks.

**Comment by shawncrawley** [comment]
```python
from hs_restclient import HydroShare, HydroShareAuthOAuth2

client_id = 'whatever_it_is'
client_secret = 'whatever_it_is'
token = {
u'access_token': u'whatever_it_is', 
u'expires_in': 2592000, 
'expires_at': 1462556350, 
u'token_type': u'Bearer', 
u'scope': u'read write', 
u'refresh_token': u'whatever_it_is'
}

auth = HydroShareAuthOAuth2(client_id, client_secret, token=token)
hs = HydroShare(auth=auth, hostname='www.hydroshare.org', use_https=True)

i = 1
for res in hs.getResourceList():
    print 'resource%s' % i
    i += 1
```
This seems to fail when processing the 6th resource in the list, because this is my output:
```bash
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
resource1
resource2
resource3
resource4
resource5
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    for res in hs.getResourceList():
  File "/usr/local/lib/python2.7/dist-packages/hs_restclient/__init__.py", line 262, in _getResultsListGenerator
    r = self._request('GET', res['next'], params=params)
  File "/usr/local/lib/python2.7/dist-packages/hs_restclient/__init__.py", line 208, in _request
    verify=self.verify)
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 310, in request
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
```

**Comment by selimnairb** [comment]
@shawncrawley Thanks.  I'll look at this later today or tomorrow and get back to you.

**Comment by selimnairb** [comment]
@shawncrawley The problem is that for whatever reason Django REST framework has decided to put HTTP links in for result pagination, rather than HTTPS.  We need to review our django/Django REST framework configuration to change this.  For now, I posted hs_restclient version 1.2.2, which patches the URL each next page when HTTPS is being used (e.g. when using OAuth).  Let me know how that goes.

**Comment by shawncrawley** [comment]
@selimnairb Thanks, with version 1.2.2 it is now working. Am I good to close this issue then?
