### ISSUE TITLE
Discover broken on www

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1109]
If I do the following on www.

1. Enter * in the Discover window on search.
2. Click the check box next to David Tarboton, under filter by Author, I get "Error, sorry an error occurred".

This appears to have been precipitated by deleting a resource that had a title, but appeared on the list as "untitled".  It may be because the SOLR database got out of sync with the delete.

I was doing this in preparation for a live demo planned for a conference tomorrow so if there is anything that can be done to fix, before my presentation at 11:30 MDT I would appreciate it.

**Comment by hyi** [comment]
@dtarb @xuezhaokun @alvacouch @mjstealey I took a look at the log and found the specifics on this internal server error pasted below. So it appears the error is indeed caused by deleting a resource in HydroShare but solr index is not updated, so it still has the index entry for the resource that does not exist any more, and then when trying to retrieve resource_type for the deleted resource, the content is NULL which raises the AttributeError. I believe this issue will be resolved when on-demand solr index update is implemented as detailed in https://github.com/hydroshare/hydroshare/issues/755 which is currently assigned to @alvacouch. Hence, I am assigning this issue to @alvacouch just to verify this would be resolved automatically once the issue https://github.com/hydroshare/hydroshare/issues/755 near real-time search index update is implemented. @dtarb Since solr index is updated nightly, there is a good chance this issue will not happen any more if you try it again this morning as long as you don't delete a resource again today before doing a search. I am sorry to say I don't think there is anything that can be done before you demo today to fix this issue, but really hope this will not affect your live demo today. I also see many permission denied errors in the log triggered from resource deletion last night, hopefully those errors are legitimate and will not affect your live demo today.
```
[06/Apr/2016 04:47:34] ERROR [django.request:256] Internal Server Error: /search/
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 125, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mezzanine/pages/middleware.py", line 95, in process_view
    return view_func(request, *view_args, **view_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/haystack/views.py", line 53, in __call__
    return self.create_response()
  File "/usr/local/lib/python2.7/dist-packages/haystack/views.py", line 147, in create_response
    return render_to_response(self.template, context, context_instance=self.context_class(self.request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 224, in render
    nodelist.append(node.render(context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 959, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 675, in resolve
    new_obj = func(obj, *arg_vals)
  File "/home/docker/hydroshare/hs_core/templatetags/hydroshare_tags.py", line 56, in resource_type
    return content.get_content_model()._meta.verbose_name
AttributeError: 'str' object has no attribute 'get_content_model'
```

**Comment by dtarb** [comment]
@hyi @alvacouch I just tried again now and I still get an error.  Even worse, if I do a search on "Tarboton" I get an error.  There is also a resource I created 4:26 am (HydroShare time) on April 6, i.e. more than 24 hours ago with title "Logan River Stream Network" that does not appear in searches based on the keyword "Logan" or "TauDEM".  TauDEM was one of the keywords I used for this resource which is public.

**Comment by hyi** [comment]
@dtarb @alvacouch @mjstealey Just checked and found the cron job for rebuilding solr index is pointing at /home/hydrobuild/hydroshare directory, but recently hydroshare build has been moved to /home/hydro/hydroshare directory. So rebuilding solr index cron job has been running on an old directory which does not have effect to the latest hydroshare deployment. I have fixed the cron job and now the solr index appears to be rebuilt correctly. Searching on "Tarboton" returns results as expected without errors now.

**Comment by dtarb** [comment]
Thanks.  I validated that the error I was getting no longer occurs, so am closing.  Pity about the live demo yesterday where I had to dance a jig and explain that the system still had errors.  But as I heard in a talk about software development once, live demos are critical to focus attention on what are the pain points, and here we found one and fixed it.
