### ISSUE TITLE
Downloads fail for resources with long file names

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1474]
Attempts to download the files in these resources individually (not the bag) fails.  This seems to be due to long file names.
https://www.hydroshare.org/resource/972d814bca094d17830be491eb659b29/ (a resource I created to reproduce the problem)
https://www.hydroshare.org/resource/162508e8a9414e409015fdfa72cbb2a9/ (a resource a user (student) created, where the problem was discovered).

**Comment by mjstealey** [comment]
> Attempts to download the files in these resources individually (not the bag) fails. This seems to be due to long file names.

Replicable: see output below

When attempting to download the singleton file from [https://www.hydroshare.org/resource/972d814bca094d17830be491eb659b29/](https://www.hydroshare.org/resource/972d814bca094d17830be491eb659b29/)

hydroshare.log output
```
[30/Sep/2016 13:04:17] ERROR [django.request:256] Internal Server Error: /django_irods/download/972d814bca094d17830be491eb659b29/data/contents/File Types In HydroShare that for testing purposes are given as a very long file name to see if hydroshare can handle such a long name.pptx
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/hydroshare/hs_tracking/middleware.py", line 14, in process_response
    session.record("visit", request.path)
  File "/hydroshare/hs_tracking/models.py", line 97, in record
    return Variable.record(*args, **kwargs)
  File "/hydroshare/hs_tracking/models.py", line 147, in record
    value=cls.encode(value))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(130)
```

As file looks in iRODS:

```
$ ils -L /hydroshareZone/home/wwwHydroProxy/972d814bca094d17830be491eb659b29/data/contents
/hydroshareZone/home/wwwHydroProxy/972d814bca094d17830be491eb659b29/data/contents:
  wwwHydroProx      0 hydroshareReplResc;hydroshareResc       312836 2016-09-30.08:54 & File Types In HydroShare that for testing purposes are given as a very long file name to see if hydroshare can handle such a long name.pptx
        generic    /projects/hydroshare/vaults/wwwProxy/home/wwwHydroProxy/972d814bca094d17830be491eb659b29/data/contents/File Types In HydroShare that for testing purposes are given as a very long file name to see if hydroshare can handle such a long name.pptx
  wwwHydroProx      1 hydroshareReplResc;mdcRRResource;hydrodata1Resource       312836 2016-09-30.08:54 & File Types In HydroShare that for testing purposes are given as a very long file name to see if hydroshare can handle such a long name.pptx
        generic    /hydro/hydrodata1ResourceVault/home/wwwHydroProxy/972d814bca094d17830be491eb659b29/data/contents/File Types In HydroShare that for testing purposes are given as a very long file name to see if hydroshare can handle such a long name.pptx
```

**Comment by hyi** [comment]
@alexlemann This error appears to trace back to hs_tracking/models.py, perhaps at this line: https://github.com/hydroshare/hydroshare/blob/develop/hs_tracking/models.py#L118 where max_length for value is define as 130. Look at the log above for details. Could you take a look and fix this issue?

**Comment by dtarb** [comment]
This can be closed when the fix is deployed and checked on beta or www.

**Comment by hyi** [comment]
Tested on beta with this resource and I can download the file with long file name without issues. So I am closing it.

**Comment by AmberSJones** [comment]
How soon will this be deployed to production? This issue is preventing our widespread use of HydroShare right now.

**Comment by hyi** [comment]
@AmberSJones The plan is to deploy the next version (1.8) to production sometime next week.

**Comment by AmberSJones** [comment]
Thanks @hyi. We look forward to it!
