### ISSUE TITLE
Stats Command - Resource Details Fails Unexpectedly

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#1524]
The `resources-details` command fails when querying resource sizes on iRODs.  This error should not cause the query to completely fail, instead the exception should be caught and written to an error log.

```
docker exec -u hydro-service hydroshare python manage.py stats --resources-details

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/hydroshare/hs_tracking/management/commands/stats.py", line 218, in handle
    self.resources_details()
  File "/hydroshare/hs_tracking/management/commands/stats.py", line 144, in resources_details
    for f in r.files.all()]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 76, in _get_size
    return self.storage.size(self.name)
  File "/hydroshare/django_irods/storage.py", line 256, in size
    stdout = self.session.run("ils", None, "-l", name)[0].split()
  File "/hydroshare/django_irods/icommands.py", line 180, in run
    raise SessionException(proc.returncode, stdout, stderr)
django_irods.icommands.SessionException: (SessionException(...), 'Error processing IRODS request: 4. stderr follows:\n\nERROR: lsUtil: srcPath /hydrotest41Zone/home/hsproxy/81e947faccf04de59392dddaac77bc75/data/contents/componentlinkagecounts.skp does not exist or user lacks access permission\n')
```

**Comment by Castronova** [comment]
This command can not be executed to send results and errors to separate files:

`docker exec -u hydro-service hydroshare python manage.py stats --resources-details 2> res-stats.err > res-stats.log`

**Comment by pkdash** [comment]
@Castronova Should this be closed?
