### ISSUE TITLE
Create Geographic Feature Resource Fails

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#1547]
I can create a new **empty** geographic feature resource using the `hs_restclient`, but I not with files. 

For example, the following code creates a new GeographicFeatureResource and then attempt to add files to it. 
```
# geographic feature resources consist of shapefiles.  First create and empty geographic feature resource
        resource_type = 'GeographicFeatureResource'
        title = 'testing_resource_please_remove'
        abstract = 'my abstract'
        keywords = ['keyword1, keyword2']
        self.resource_id = self.hs.createResource(resource_type=resource_type,
                                             title=title,
                                             abstract=abstract,
                                             keywords=keywords)

        # add multiple files to this existing resource
        resource_files = ['./test_data/geographicfeature/logannet.dbf',
                          './test_data/geographicfeature/logannet.prj',
                          './test_data/geographicfeature/logannet.shp',
                          './test_data/geographicfeature/logannet.shp.xml',
                          './test_data/geographicfeature/logannet.shx']

        for f in resource_files:
            res = self.hs.addResourceFile(self.resource_id, f)
```

```
Error
Traceback (most recent call last):
  File "/Users/castro/Documents/work/scripts/hs_api/create_geographic_resource.py", line 92, in testCreateGeographicFeature
    res = self.hs.addResourceFile(self.resource_id, f)
  File "build/bdist.macosx-10.6-x86_64/egg/hs_restclient/__init__.py", line 769, in addResourceFile
    raise HydroShareHTTPException((url, 'POST', r.status_code))
HydroShareHTTPException: Received status 400 Bad Request when accessing https://www.hydroshare.org/hsapi/resource/3c8e8d1591fc4c189b87370e87f1885c/files/ with method POST and params None.
```

This also fails when trying to create a Geographic Feature Resource using a shapefile archive.

**Comment by Castronova** [comment]
This may have something to do with the app trying to parse metadata from the uploaded files.  We currently cannot upload multiple files at once using the rest api, i.e. they must be added on at a time.  Implementing multiple file upload during resource creation could potentially fix this issue.

**Comment by dtarb** [comment]
@Castronova is this still an issue.

**Comment by Castronova** [comment]
@dtarb This is still not fixed.  As far as I know, only one file can be added to a resource at a time vai the rest API.  I think the geographic resource fails during its auto metadata population phase when uploading shapefiles (i.e. *.dbf, *.prj, *.shp, *.shp.xml, and *.shx) individually.  The code below fails with the `GeographicFeatureResource` but works fine with the `GenericResource`:

```
import os
import creds
from glob import glob
from hs_restclient import HydroShare, HydroShareAuthBasic

auth = HydroShareAuthBasic(username=creds.username, password=creds.password)
hs = HydroShare(auth=auth)

abstract = 'My test GIS resource'
title = 'REMOVE - My test GIS resource'
keywords = ('GIS', 'API', 'TEST')
rtype = 'GeographicFeatureResource'

files = glob('data/*')
# files = [
#           data/logannet.dbf
#           data/logannet.prj
#           data/logannet.shp
#           data/logannet.shp.xml
#           data/logannet.shx
#         ]

try:
    # create an empty resource
    print('Creating resource...', end='', flush=True)
    resource_id = hs.createResource(rtype,
                                    title,
                                    keywords=keywords,
                                    abstract=abstract)
    print(' done')

    # add the GIS files
    print('Adding data files...', end='', flush=True)
    for f in files:
        print('.', end='', flush=True)
        hs.addResourceFile(resource_id, f)
    print(' done')
except Exception as e:
    print('ERROR: %s' % e)
finally:
    print('Cleaning up...', end='', flush=True)
    hs.deleteResource(resource_id)
    print(' done')
```

```
$ ./test.py

Creating resource... done
Adding data files....ERROR: Received status 400 Bad Request when accessing https://www.hydroshare.org/hsapi/resource/d47d65fb1be244a4a169ee58ac2e55b3/files/ with method POST and params None.
Cleaning up... done
```

**Comment by pkdash** [comment]
@Castronova Instead of adding files individually (which will obviously fail for Geographic Feature resource) add a zip file that contains all the files that are part of the shape file.

**Comment by dtarb** [comment]
Closing as no longer relevant with composite resources.
