### ISSUE TITLE
Update Dockerfile - 1.8.0

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1587]
Add xmltodict
`pip install xmltodict==0.10.2`

Update python iRODS client
`-e git+https://github.com/irods/python-irodsclient.git@25512a0fca3eef29cb053d9fb6cf549f0d99985b#egg=python_irodsclient`

Update Django REST 3.5.3 (per email with @alvacouch)
`djangorestframework==3.5.3`

**Comment by mjstealey** [comment]
Updated image: mjstealey/hs_docker_base:1.8.0

Output from `run-tests` script

```
$ docker exec -u hydro-service hydroshare ./run-tests
No handlers could be found for logger "hydroshare"
/usr/local/lib/python2.7/site-packages/mezzanine/utils/conf.py:55: UserWarning: TIME_ZONE setting is not set, using closest match: Etc/UTC
  warn("TIME_ZONE setting is not set, using closest match: %s" % tz)
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py:161: RemovedInDjango19Warning: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ContentType(models.Model):

/usr/local/lib/python2.7/site-packages/autocomplete_light/widgets.py:19: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  from django.forms.util import flatatt

/usr/local/lib/python2.7/site-packages/autocomplete_light/fields.py:8: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import GenericForeignKey

...........................................................Trying `CDLL(libgeos_c.so.1)`
Library path: 'libgeos_c.so.1'
DLL: <CDLL 'libgeos_c.so.1', handle 1b8e8f0 at 7fd7e0fde490>
Trying `CDLL(libc.so.6)`
Library path: 'libc.so.6'
DLL: <CDLL 'libc.so.6', handle 7fd803105000 at 7fd7e0fdeb10>
..2016-11-13 22:05:33,830 pysolr-DEBUG [/usr/local/lib/python2.7/site-packages/pysolr.py 352] Starting request to 'http://172.17.0.6:8983/solr/update/?commit=true' (post) with body 'u'<delete>'...
2016-11-13 22:05:33,844 requests.packages.urllib3.connectionpool-DEBUG [/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py 387] "POST /solr/update/?commit=true HTTP/1.1" 200 None
2016-11-13 22:05:33,847 pysolr-INFO [/usr/local/lib/python2.7/site-packages/pysolr.py 386] Finished 'http://172.17.0.6:8983/solr/update/?commit=true' (post) with body 'u'<delete>' in 0.015 seconds.
----------------------------------------------------------------------
Ran 411 tests in 1064.772s

OK (SKIP=1)
nosetests corsheaders theme theme.blog_mods heartbeat haystack hs_core hs_access_control hs_labels hs_metrics irods_browser_app hs_geo_raster_resource ref_ts hs_app_timeseries hs_app_netCDF hs_model_program hs_modelinstance hs_tools_resource hs_swat_modelinstance hs_geographic_feature_resource hs_script_resource hs_sitemap hs_collection_resource hs_modflow_modelinstance hs_tracking debug_toolbar filebrowser_safe django_comments --verbosity=1
Creating test database for alias 'default'...
Deleted all resource specific metadata for all timeseries resources.
Copy resource to temp folder failure: Number: 0 List: []
VRT file update success: Number: 0 List[]
VRT file update fail: Number: 0 List[]
Meta update success: Number: 0 List []
Meta update fail: Number: 0 List []
Destroying test database for alias 'default'...
Name                                                Stmts   Miss  Cover
-----------------------------------------------------------------------
hs_access_control/__init__.py                           0      0   100%
hs_access_control/models.py                           722     90    88%
hs_app_netCDF/__init__.py                               0      0   100%
hs_app_netCDF/admin.py                                  4      0   100%
hs_app_netCDF/forms.py                                121     16    87%
hs_app_netCDF/models.py                               153     41    73%
hs_app_netCDF/nc_functions/__init__.py                  0      0   100%
hs_app_netCDF/nc_functions/nc_dump.py                  88     75    15%
hs_app_netCDF/nc_functions/nc_meta.py                 208    186    11%
hs_app_netCDF/nc_functions/nc_utils.py                179    157    12%
hs_app_netCDF/page_processors.py                       78     67    14%
hs_app_netCDF/receivers.py                            265    228    14%
hs_app_netCDF/serialization.py                        330    166    50%
hs_app_timeseries/__init__.py                           1      0   100%
hs_app_timeseries/admin.py                              4      0   100%
hs_app_timeseries/apps.py                               5      0   100%
hs_app_timeseries/forms.py                            365    212    42%
hs_app_timeseries/models.py                          1098    182    83%
hs_app_timeseries/page_processors.py                  155    138    11%
hs_app_timeseries/receivers.py                        567     78    86%
hs_app_timeseries/views.py                             23      5    78%
hs_collection_resource/__init__.py                      1      0   100%
hs_collection_resource/admin.py                         4      0   100%
hs_collection_resource/apps.py                          5      0   100%
hs_collection_resource/models.py                       36      3    92%
hs_collection_resource/page_processors.py              35     28    20%
hs_collection_resource/patches/__init__.py              0      0   100%
hs_collection_resource/receivers.py                    20     12    40%
hs_collection_resource/urls.py                          3      0   100%
hs_collection_resource/utils.py                        74     11    85%
hs_collection_resource/views.py                       171     15    91%
hs_core/__init__.py                                     1      0   100%
hs_core/admin.py                                        9      0   100%
hs_core/apps.py                                         5      0   100%
hs_core/autocomplete_light_registry.py                 29     18    38%
hs_core/discovery_form.py                              71     58    18%
hs_core/forms.py                                      757    437    42%
hs_core/hydro_realtime_signal_processor.py             46      6    87%
hs_core/hydroshare/__init__.py                          4      0   100%
hs_core/hydroshare/date_util.py                        53     15    72%
hs_core/hydroshare/discovery.py                         8      4    50%
hs_core/hydroshare/hs_bagit.py                        150     39    74%
hs_core/hydroshare/resource.py                        397    171    57%
hs_core/hydroshare/users.py                           231    115    50%
hs_core/hydroshare/utils.py                           510    183    64%
hs_core/languages_iso.py                                1      0   100%
hs_core/management/__init__.py                          0      0   100%
hs_core/management/commands/__init__.py                 0      0   100%
hs_core/metadata_terms_urls.py                          3      0   100%
hs_core/models.py                                    1318    251    81%
hs_core/page_processors.py                            239    225     6%
hs_core/receivers.py                                   79     46    42%
hs_core/resourcemap_urls.py                             4      0   100%
hs_core/search_indexes.py                             245     67    73%
hs_core/serialization.py                              946    399    58%
hs_core/signals.py                                     11      0   100%
hs_core/tasks.py                                      142     73    49%
hs_core/templatetags/__init__.py                        0      0   100%
hs_core/templatetags/hydroshare_tags.py                90     47    48%
hs_core/testing.py                                     11      0   100%
hs_core/urls.py                                         3      0   100%
hs_core/views/__init__.py                             871    538    38%
hs_core/views/autocomplete.py                          46     40    13%
hs_core/views/discovery_json_view.py                   35     27    23%
hs_core/views/discovery_view.py                        47     37    21%
hs_core/views/pagination.py                             3      0   100%
hs_core/views/resource_folder_hierarchy.py            177    161     9%
hs_core/views/resource_rest_api.py                    352     77    78%
hs_core/views/serializers.py                           87     14    84%
hs_core/views/user_rest_api.py                         12      0   100%
hs_core/views/utils.py                                331    125    62%
hs_core/xmlparser.py                                   42      8    81%
hs_geo_raster_resource/__init__.py                      0      0   100%
hs_geo_raster_resource/admin.py                         4      0   100%
hs_geo_raster_resource/forms.py                       155     93    40%
hs_geo_raster_resource/models.py                      155     18    88%
hs_geo_raster_resource/page_processors.py              56     47    16%
hs_geo_raster_resource/raster_meta_extract.py         137     29    79%
hs_geo_raster_resource/receivers.py                   256     70    73%
hs_geo_raster_resource/serialization.py               341    210    38%
hs_geographic_feature_resource/__init__.py              1      0   100%
hs_geographic_feature_resource/admin.py                 4      0   100%
hs_geographic_feature_resource/apps.py                  5      0   100%
hs_geographic_feature_resource/forms.py                65     26    60%
hs_geographic_feature_resource/models.py              115     25    78%
hs_geographic_feature_resource/page_processors.py      72     65    10%
hs_geographic_feature_resource/parse_lib.py           118     15    87%
hs_geographic_feature_resource/receivers.py           454    133    71%
hs_labels/__init__.py                                   0      0   100%
hs_labels/models.py                                   121      3    98%
hs_labels/urls.py                                       3      0   100%
hs_labels/views/__init__.py                            52     47    10%
hs_metrics/__init__.py                                  0      0   100%
hs_metrics/models.py                                    0      0   100%
hs_metrics/urls.py                                      3      0   100%
hs_metrics/views.py                                    65     49    25%
hs_model_program/__init__.py                            0      0   100%
hs_model_program/admin.py                               4      0   100%
hs_model_program/forms.py                              48     21    56%
hs_model_program/models.py                             85      6    93%
hs_model_program/page_processors.py                    23     17    26%
hs_model_program/receivers.py                          33     24    27%
hs_model_program/urls.py                                3      0   100%
hs_model_program/views.py                              19     14    26%
hs_modelinstance/__init__.py                            0      0   100%
hs_modelinstance/admin.py                               4      0   100%
hs_modelinstance/forms.py                              55     25    55%
hs_modelinstance/models.py                             93      7    92%
hs_modelinstance/page_processors.py                    28     20    29%
hs_modelinstance/receivers.py                          22     14    36%
hs_modflow_modelinstance/__init__.py                    1      0   100%
hs_modflow_modelinstance/admin.py                       4      0   100%
hs_modflow_modelinstance/apps.py                        5      0   100%
hs_modflow_modelinstance/forms.py                     229     85    63%
hs_modflow_modelinstance/models.py                    448     33    93%
hs_modflow_modelinstance/page_processors.py            63     53    16%
hs_modflow_modelinstance/receivers.py                  59     49    17%
hs_script_resource/__init__.py                          0      0   100%
hs_script_resource/admin.py                             4      0   100%
hs_script_resource/forms.py                            29     10    66%
hs_script_resource/models.py                           71     27    62%
hs_script_resource/page_processors.py                  29     22    24%
hs_script_resource/receivers.py                        48     12    75%
hs_sitemap/__init__.py                                  0      0   100%
hs_sitemap/views.py                                     6      2    67%
hs_swat_modelinstance/__init__.py                       1      0   100%
hs_swat_modelinstance/admin.py                          4      0   100%
hs_swat_modelinstance/apps.py                           5      0   100%
hs_swat_modelinstance/forms.py                        174     70    60%
hs_swat_modelinstance/models.py                       276     23    92%
hs_swat_modelinstance/page_processors.py               42     35    17%
hs_swat_modelinstance/receivers.py                     46     36    22%
hs_swat_modelinstance/serialization.py                293     29    90%
hs_tools_resource/__init__.py                           1      0   100%
hs_tools_resource/admin.py                              4      0   100%
hs_tools_resource/apps.py                               5      0   100%
hs_tools_resource/forms.py                            123     40    67%
hs_tools_resource/models.py                           150     48    68%
hs_tools_resource/page_processors.py                   60     53    12%
hs_tools_resource/receivers.py                         33      9    73%
hs_tools_resource/utils.py                             14      0   100%
hs_tracking/__init__.py                                 1      0   100%
hs_tracking/apps.py                                     5      0   100%
hs_tracking/management/__init__.py                      0      0   100%
hs_tracking/management/commands/__init__.py             0      0   100%
hs_tracking/middleware.py                               9      1    89%
hs_tracking/models.py                                 109      7    94%
hs_tracking/signals.py                                  9      0   100%
hs_tracking/tests.py                                  136      0   100%
hs_tracking/views.py                                   40      2    95%
hydroshare/__init__.py                                 10      1    90%
hydroshare/celery.py                                   11      1    91%
hydroshare/local_settings.py                           83      0   100%
hydroshare/settings.py                                 69      2    97%
hydroshare/urls.py                                     29      0   100%
irods_browser_app/__init__.py                           0      0   100%
irods_browser_app/models.py                             0      0   100%
irods_browser_app/urls.py                               3      0   100%
irods_browser_app/views.py                            146    130    11%
manage.py                                               8      0   100%
ref_ts/__init__.py                                      0      0   100%
ref_ts/admin.py                                         4      0   100%
ref_ts/forms.py                                        15      0   100%
ref_ts/models.py                                       98     43    56%
ref_ts/page_processors.py                              21     16    24%
ref_ts/receivers.py                                    47     39    17%
ref_ts/ts_utils.py                                    449    412     8%
ref_ts/urls.py                                          3      0   100%
ref_ts/views.py                                       223    191    14%
theme/__init__.py                                       0      0   100%
theme/admin.py                                         12      0   100%
theme/blog_mods/__init__.py                             0      0   100%
theme/blog_mods/admin.py                                7      3    57%
theme/blog_mods/models.py                               0      0   100%
theme/forms.py                                        180    114    37%
theme/models.py                                        97     12    88%
theme/templatetags/__init__.py                          0      0   100%
theme/views.py                                        202    160    21%
-----------------------------------------------------------------------
TOTAL                                               18933   7639    60%
```

**Comment by mjstealey** [comment]
dockerworker container exits with

```
[2016-11-13 22:31:58,154: ERROR/MainProcess] Unrecoverable error: TypeError("object of type 'Exchange' has no len()",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 609, in start
    c.connection, on_decode_error=c.on_decode_error,
  File "/usr/local/lib/python2.7/site-packages/celery/app/amqp.py", line 385, in __init__
    **kw
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 364, in __init__
    self.revive(self.channel)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 376, in revive
    self.declare()
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 386, in declare
    queue.declare()
  File "/usr/local/lib/python2.7/site-packages/kombu/entity.py", line 522, in declare
    self.queue_declare(nowait, passive=False)
  File "/usr/local/lib/python2.7/site-packages/kombu/entity.py", line 548, in queue_declare
    nowait=nowait)
  File "/usr/local/lib/python2.7/site-packages/amqp/channel.py", line 1248, in queue_declare
    args.write_shortstr(queue)
  File "/usr/local/lib/python2.7/site-packages/amqp/serialization.py", line 324, in write_shortstr
    if len(s) > 255:
TypeError: object of type 'Exchange' has no len()
```

**Comment by mjstealey** [comment]
Output of `pip freeze`

```
# pip freeze
amqp==1.4.9
anyjson==0.3.3
arrow==0.7.0
astroid==1.4.8
autoflake==0.6.6
autopep8==1.2.2
bagit==1.5.4
beautifulsoup4==4.4.1
billiard==3.3.0.23
bleach==1.4.3
celery==3.1.23
chardet==2.3.0
colorama==0.3.7
coverage==4.0.3
cycler==0.10.0
defusedexpat==0.4
defusedxml==0.4.1
Django==1.8.14
django-appconf==1.0.2
django-autocomplete-light==2.0.9
django-braces==1.10.0
django-compressor==2.0
django-contrib-comments==1.6.2
django-cors-headers==1.1.0
django-crispy-forms==1.6.0
django-debug-toolbar==1.4
django-haystack==2.4.1
django-heartbeat==2.0.2
django-inplaceedit==1.4.1
django-jsonfield==0.9.19
django-modeltranslation==0.11
django-nose==1.4.3
django-oauth-toolkit==0.10.0
django-timedeltafield==0.7.10
django-widget-tweaks==1.4.1
djangorestframework==3.5.3
docker-py==1.7.2
ecdsa==0.13
filebrowser-safe==0.4.3
flake8==2.5.4
funcsigs==1.0.2
future==0.15.2
GDAL==2.1.0
geojson==1.3.2
gevent==1.1.2
google.foresite-toolkit==1.3
grappelli-safe==0.4.2
greenlet==0.4.10
gunicorn==19.6.0
html5lib==0.9999999
isodate==0.5.4
keepalive==0.5
kombu==3.0.37
lazy-object-proxy==1.2.2
lxml==3.6.0
mapnik==0.1
matplotlib==1.5.1
mccabe==0.4.0
Mezzanine==4.1.0
mock==1.3.0
netCDF4==1.2.4
nose==1.3.7
numpy==1.10.4
oauthlib==1.0.3
OWSLib==0.10.3
pandas==0.18.0
paramiko==1.16.0
pbr==1.10.0
pep8==1.7.0
Pillow==3.1.1
prettytable==0.7.2
psutil==4.0.0
psycopg2==2.6.1
py2-ipaddress==3.4.1
PyCRS==0.1.3
pycrypto==2.6.1
pyflakes==1.1.0
pylint==1.5.5
pyparsing==2.1.10
pyproj==1.9.5.1
pysolr==3.4.0
pysqlite==2.8.1
python-dateutil==2.6.0
-e git+https://github.com/irods/python-irodsclient.git@25512a0fca3eef29cb053d9fb6cf549f0d99985b#egg=python_irodsclient
pytz==2016.3
rcssmin==1.0.6
rdflib==4.0.1
redis==2.10.5
requests==2.9.1
requests-oauthlib==0.6.1
rjsmin==1.0.12
sh==1.11
Shapely==1.5.13
six==1.10.0
SPARQLWrapper==1.7.6
sqlparse==0.2.2
suds-jurko==0.6
tzlocal==1.2.2
virtualenv==15.0.2
websocket-client==0.37.0
wrapt==1.10.8
xmltodict==0.10.2
```

**Comment by mjstealey** [comment]
updated Dockerfile is pushed to [PR 1614](https://github.com/hydroshare/hydroshare/pull/1614/files)
