### ISSUE TITLE
SOLR references non-existent BaseResource.rating field

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1611]
In testing, SOLR raises log errors about trying to index on BaseResource.rating, which has apparently been deleted. The SOLR schema should omit this field. This is causing whole records not to be indexed in SOLR. Error message: 

```Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=hs_core.baseresource.9] unknown field 'rating']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/haystack/backends/solr_backend.py", line 72, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 860, in add
    return self._update(m, commit=commit, softCommit=softCommit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 462, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 394, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
SolrError: Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=hs_core.baseresource.9] unknown field 'rating']```

**Comment by alvacouch** [comment]
Closed due to further testing.
