### ISSUE TITLE
Lack of REST API decorators causes uncaught exceptions in system log

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2123]
@pkdash @hyi @Maurier @aphelionz @dtarb I have been monitoring the system logs for problems unseen so far. I am working from the 1.10.0 release candidate. There are a lot of messages like this: 
```
[14/May/2017 14:24:37] ERROR Internal Server Error: /hsapi/_internal/6041109de34f4ab2b8c82b6982d71311/creator/add-metadata/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/hydroshare/hs_core/views/__init__.py", line 270, in add_metadata_element
    res, _, _ = authorize(request, shortkey, needed_permission=ACTION_TO_AUTHORIZE.EDIT_RESOURCE)
  File "/hydroshare/hs_core/views/utils.py", line 222, in authorize
    raise PermissionDenied()
PermissionDenied: You do not have permission to perform this action.
[14/May/2017 14:24:38] ERROR Internal Server Error: /hsapi/_internal/6041109de34f4ab2b8c82b6982d71311/creator/add-metadata/

```
Looking further, these result from lack of decorators on the REST API functions, so that raised exceptions are not caught by the REST system and are treated as system errors. Solution is to appropriately decorate the REST functions.

**Comment by martinseul** [comment]
Stale, close
