### ISSUE TITLE
Cannot use settings constants in mezzanine views + templates

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2597]
We were trying to put the RECAPTCHA_SITE_KEY in the local_settings.py for use inside a template. The documentation says to use the `register_settings` function for this purpose. However, adding this code from their [example](http://mezzanine.jupo.org/docs/configuration.html#registering-settings):

```
from mezzanine.conf import register_setting

register_setting(
    name="AUTHORS_BOOKS_PER_PAGE",
    label="Authors books per page",
    description="The number of books to show per author page.",
    editable=True,
    default=10,
)
```

Causes the app to crash with this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/hydroshare/hydroshare/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/hydroshare/hydroshare/settings.py", line 462, in <module>
    local_settings = __import__(local_settings_module, globals(), locals(), ['*'])
  File "/hydroshare/hydroshare/local_settings.py", line 11, in <module>
    from mezzanine.conf import register_setting
  File "/usr/local/lib/python2.7/site-packages/mezzanine/conf/__init__.py", line 253, in <module>
    for app in sorted(django_settings.INSTALLED_APPS, key=mezz_first):
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 113, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

**Comment by aphelionz** [comment]
@alexlemann any ideas?

**Comment by phuongdm** [comment]
Could we use a temporary key then replace by the key in local_setting.py?

**Comment by aphelionz** [comment]
@phuongdm nah, that's what this ticket is about. The sign-up view is controlled by the mezzanine and for some reason using their approach causes a crash.

**Comment by aphelionz** [comment]
@hyi you solved this right?

**Comment by hyi** [comment]
@aphelionz Right. Feel free to close this.
