### ISSUE TITLE
Composite resource to support File Set - a new aggregation type

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2808]

**Comment by sblack-usu** [comment]
@pkdash - I'm having trouble deploying to beta.  Any ideas what's going on?
stacktrace during migrations
```
Running migrations:
  Applying hs_file_types.0009_auto_20181028_1554...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 88, in database_forwards
    field,
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 445, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: column "resource_id" contains null values
```
stacktrace in solr (probably because migrations failed)
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/haystack/management/commands/rebuild_index.py", line 42, in handle
    call_command('update_index', **update_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 230, in handle
    self.update_backend(label, using)
  File "/usr/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 276, in update_backend
    last_max_pk=max_pk)
  File "/usr/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 97, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/usr/local/lib/python2.7/site-packages/haystack/backends/solr_backend.py", line 60, in update
    docs.append(index.full_prepare(obj))
  File "/usr/local/lib/python2.7/site-packages/haystack/indexes.py", line 208, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/usr/local/lib/python2.7/site-packages/haystack/indexes.py", line 202, in prepare
    value = getattr(self, "prepare_%s" % field_name)(obj)
  File "/hydroshare/hs_core/search_indexes.py", line 554, in prepare_content_type
    for f in obj.logical_files:
  File "/hydroshare/hs_core/models.py", line 2260, in logical_files
    if res_file.logical_file is not None:
  File "/hydroshare/hs_core/models.py", line 2955, in logical_file
    return self.logical_file_content_object
  File "/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py", line 258, in __get__
    rel_obj = ct.get_object_for_this_type(pk=pk_val)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 174, in get_object_for_this_type
    return self.model_class()._base_manager.using(self._state.db).get(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
django.db.utils.ProgrammingError: column hs_file_types_genericlogicalfile.resource_id does not exist
LINE 1: SELECT "hs_file_types_genericlogicalfile"."id", "hs_file_typ...
```

**Comment by pkdash** [comment]
@sblack-usu I think that migration file 'hs_file_types.0009_auto_20181028_1554.py' is NOT correct. I have to fix it. The resource (FK) field needs to be set to null=True instead of default=None.

**Comment by pkdash** [comment]
@sblack-usu I have a PR that fixes this migration issue: https://github.com/hydroshare/hydroshare/pull/3038

**Comment by Maurier** [comment]
I will be pushing a fix for a minor bug introduced in this issue:
![image](https://user-images.githubusercontent.com/2448568/49885224-e96e4b80-fdf3-11e8-9d9c-48bfa158fbdc.png)

**Comment by sblack-usu** [comment]
Thanks for catching that @Maurier.  Just submit a PR against develop when you're ready and we can get this into 1.18.

**Comment by Maurier** [comment]
@pkdash @sblack-usu PR here: https://github.com/hydroshare/hydroshare/pull/3042
Please review when you get a chance.
