### ISSUE TITLE
rebuild --db fails

### ISSUE THREAD

**Issue by izphi78** [hydroshare/hydroshare#3617]
When I try to execute the "hsctl rebuild --db" command, the script fails while executing

docker exec -u hydro-service hydroshare python manage.py collectstatic -v0 --noinput

<details><summary>Output</summary><p>

# docker exec hydroshare python manage.py rebuild_index --noinput
/usr/local/lib/python2.7/site-packages/mezzanine/utils/conf.py:73: UserWarning: TIME_ZONE setting is not set, using closest match: Etc/UTC
  warn("TIME_ZONE setting is not set, using closest match: %s" % tz)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/hydroshare/hs_core/models.py", line 13, in <module>
    from django_irods.icommands import SessionException
  File "/hydroshare/django_irods/icommands.py", line 263, in <module>
    GLOBAL_SESSION.run('iinit', None, GLOBAL_ENVIRONMENT.auth)
  File "/hydroshare/django_irods/icommands.py", line 182, in run
    raise SessionException(proc.returncode, stdout, stderr)
django_irods.icommands.SessionException: (SessionException(...), 'Error processing IRODS request: 7. stderr follows:\n\n[-]\t/tmp/tmprBqCHO/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]\n\n failed with error -826000 CAT_INVALID_AUTHENTICATION \n')
  - docker exec -u hydro-service hydroshare rm -f hydroshare/static/robots.txt
MIGRATE:
  - docker exec -u hydro-service hydroshare python manage.py migrate sites --noinput
/usr/local/lib/python2.7/site-packages/mezzanine/utils/conf.py:73: UserWarning: TIME_ZONE setting is not set, using closest match: Etc/UTC
  warn("TIME_ZONE setting is not set, using closest match: %s" % tz)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/hydroshare/hs_core/models.py", line 13, in <module>
    from django_irods.icommands import SessionException
  File "/hydroshare/django_irods/icommands.py", line 263, in <module>
    GLOBAL_SESSION.run('iinit', None, GLOBAL_ENVIRONMENT.auth)
  File "/hydroshare/django_irods/icommands.py", line 182, in run
    raise SessionException(proc.returncode, stdout, stderr)
django_irods.icommands.SessionException: (SessionException(...), 'Error processing IRODS request: 7. stderr follows:\n\n[-]\t/tmp/tmprBqCHO/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]\n\n failed with error -826000 CAT_INVALID_AUTHENTICATION \n')
  - docker exec -u hydro-service hydroshare python manage.py migrate --fake-initial --noinput
/usr/local/lib/python2.7/site-packages/mezzanine/utils/conf.py:73: UserWarning: TIME_ZONE setting is not set, using closest match: Etc/UTC
  warn("TIME_ZONE setting is not set, using closest match: %s" % tz)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/hydroshare/hs_core/models.py", line 13, in <module>
    from django_irods.icommands import SessionException
  File "/hydroshare/django_irods/icommands.py", line 263, in <module>
    GLOBAL_SESSION.run('iinit', None, GLOBAL_ENVIRONMENT.auth)
  File "/hydroshare/django_irods/icommands.py", line 182, in run
    raise SessionException(proc.returncode, stdout, stderr)
django_irods.icommands.SessionException: (SessionException(...), 'Error processing IRODS request: 7. stderr follows:\n\n[-]\t/tmp/tmprBqCHO/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]\n\n failed with error -826000 CAT_INVALID_AUTHENTICATION \n')
  - docker exec -u hydro-service hydroshare python manage.py fix_permissions
/usr/local/lib/python2.7/site-packages/mezzanine/utils/conf.py:73: UserWarning: TIME_ZONE setting is not set, using closest match: Etc/UTC
  warn("TIME_ZONE setting is not set, using closest match: %s" % tz)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/hydroshare/hs_core/models.py", line 13, in <module>
    from django_irods.icommands import SessionException
  File "/hydroshare/django_irods/icommands.py", line 263, in <module>
    GLOBAL_SESSION.run('iinit', None, GLOBAL_ENVIRONMENT.auth)
  File "/hydroshare/django_irods/icommands.py", line 182, in run
    raise SessionException(proc.returncode, stdout, stderr)
django_irods.icommands.SessionException: (SessionException(...), 'Error processing IRODS request: 7. stderr follows:\n\n[-]\t/tmp/tmprBqCHO/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]\n\n failed with error -826000 CAT_INVALID_AUTHENTICATION \n')
SOLR SCHEMA:
 - docker exec solr bin/solr create_core -c collection1 -n basic_config

Copying configuration to new core instance directory:
/opt/solr/server/solr/collection1

Creating new core 'collection1' using command:
http://localhost:8983/solr/admin/cores?action=CREATE&name=collection1&instanceDir=collection1

{
  "responseHeader":{
    "status":0,
    "QTime":4013},
  "core":"collection1"}

  - docker exec hydroshare python manage.py build_solr_schema -f schema.xml
/usr/local/lib/python2.7/site-packages/mezzanine/utils/conf.py:73: UserWarning: TIME_ZONE setting is not set, using closest match: Etc/UTC
  warn("TIME_ZONE setting is not set, using closest match: %s" % tz)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/hydroshare/hs_core/models.py", line 13, in <module>
    from django_irods.icommands import SessionException
  File "/hydroshare/django_irods/icommands.py", line 263, in <module>
    GLOBAL_SESSION.run('iinit', None, GLOBAL_ENVIRONMENT.auth)
  File "/hydroshare/django_irods/icommands.py", line 182, in run
    raise SessionException(proc.returncode, stdout, stderr)
django_irods.icommands.SessionException: (SessionException(...), 'Error processing IRODS request: 7. stderr follows:\n\n[-]\t/tmp/tmprBqCHO/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]\n\n failed with error -826000 CAT_INVALID_AUTHENTICATION \n')
  - docker exec solr cp /hydroshare/schema.xml /opt/solr/example/solr/collection1/conf/schema.xml
cp: cannot stat '/hydroshare/schema.xml': No such file or directory
  - docker exec solr sed -i '/<schemaFactory class="ManagedIndexSchemaFactory">/,+4d' /opt/solr/server/solr/collection1/conf/solrconfig.xml
  - docker exec solr rm /opt/solr/server/solr/collection1/conf/managed-schema
SOLR RELOAD
  - docker exec hydroshare curl "solr:8983/solr/admin/cores?action=RELOAD&core=collection1"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader"><int name="status">500</int><int name="QTime">107</int></lst><lst name="error"><lst name="metadata"><str name="error-class">org.apache.solr.common.SolrException</str><str name="root-error-class">org.apache.solr.core.SolrResourceNotFoundException</str></lst><str name="msg">Error handling 'reload' action</str><str name="trace">org.apache.solr.common.SolrException: Error handling 'reload' action
	at org.apache.solr.handler.admin.CoreAdminOperation.lambda$static$2(CoreAdminOperation.java:113)
	at org.apache.solr.handler.admin.CoreAdminOperation.execute(CoreAdminOperation.java:384)
	at org.apache.solr.handler.admin.CoreAdminHandler$CallInfo.call(CoreAdminHandler.java:388)
	at org.apache.solr.handler.admin.CoreAdminHandler.handleRequestBody(CoreAdminHandler.java:174)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
	at org.apache.solr.servlet.HttpSolrCall.handleAdmin(HttpSolrCall.java:749)
	at org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:730)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:510)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:361)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:305)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Unable to reload core [collection1]
	at org.apache.solr.core.CoreContainer.reload(CoreContainer.java:1189)
	at org.apache.solr.handler.admin.CoreAdminOperation.lambda$static$2(CoreAdminOperation.java:111)
	... 36 more
Caused by: org.apache.solr.common.SolrException: Could not load conf for core collection1: Error loading both non-managed schema 'schema.xml' and managed schema 'managed-schema'
100  5422  100  5422    0     0  27788      0 --:--:-- --:--:-- --:--:-- 27948
figSetService.getConfig(ConfigSetService.java:97)
	at org.apache.solr.core.CoreContainer.reload(CoreContainer.java:1181)
	... 37 more
Caused by: org.apache.solr.common.SolrException: Error loading both non-managed schema 'schema.xml' and managed schema 'managed-schema'
	at org.apache.solr.schema.ManagedIndexSchemaFactory.readSchemaLocally(ManagedIndexSchemaFactory.java:213)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:118)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.create(ManagedIndexSchemaFactory.java:45)
	at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:75)
	at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:119)
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:92)
	... 38 more
Caused by: org.apache.solr.core.SolrResourceNotFoundException: Can't find resource 'schema.xml' in classpath or '/opt/solr/server/solr/collection1'
	at org.apache.solr.core.SolrResourceLoader.openResource(SolrResourceLoader.java:405)
	at org.apache.solr.core.SolrResourceLoader.openSchema(SolrResourceLoader.java:352)
	at org.apache.solr.schema.ManagedIndexSchemaFactory.readSchemaLocally(ManagedIndexSchemaFactory.java:206)
	... 43 more
</str><int name="code">500</int></lst>
</response>
REBUILD SOLR INDEX:
  - docker exec hydroshare python manage.py rebuild_index --noinput
/usr/local/lib/python2.7/site-packages/mezzanine/utils/conf.py:73: UserWarning: TIME_ZONE setting is not set, using closest match: Etc/UTC
  warn("TIME_ZONE setting is not set, using closest match: %s" % tz)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/hydroshare/hs_core/models.py", line 13, in <module>
    from django_irods.icommands import SessionException
  File "/hydroshare/django_irods/icommands.py", line 263, in <module>
    GLOBAL_SESSION.run('iinit', None, GLOBAL_ENVIRONMENT.auth)
  File "/hydroshare/django_irods/icommands.py", line 182, in run
    raise SessionException(proc.returncode, stdout, stderr)
django_irods.icommands.SessionException: (SessionException(...), 'Error processing IRODS request: 7. stderr follows:\n\n[-]\t/tmp/tmprBqCHO/plugins/auth/native/libnative.cpp:342:irods::error native_auth_client_response(irods::plugin_context &, rcComm_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]\n\n failed with error -826000 CAT_INVALID_AUTHENTICATION \n')
[...]

</p></details>

I am using the provided [VM](http://distribution.hydroshare.org/public_html/hydrodev-lubuntu-18.04-26-10-2018.ova) and I am on the current master branch.

But nevertheless it happens on all releases. 

So I thought it might be something related to me or especially my network.
To omit the filtered research-network I am currently working in I used a VPN with the same result.

At this point I am clueless and would be really happy for any help.

Here is the [full output](https://github.com/hydroshare/hydroshare/files/3702040/log.txt) of the rebuild command.

If you need further information please let me know. I am more than happy to provide them.

Thanks in advance!

**Comment by cuahsimarko** [comment]
The official docs I've seen new Engineers use for developer setup are here https://docs.google.com/document/d/1_8ClNiIBVSEI3jY4UJKOWrV6uwKilKug-69LoVizezk/edit?ts=5d9e54b8 there's some legacy capability available "as-is", dating back 5-7 years and that community communicates in-person or via email for tips and tricks...

**Comment by izphi78** [comment]
thanks a lot, that solved my problem!
