### ISSUE TITLE
web app connector logged error

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3770]
I see this message in our logs frequently.  Investigate what's going on and handle the exception properly.

```
[25/Feb/2020 21:15:58] ERROR [hs_tools_resource.utils:40] [WebApp] 'https://mygeohub.org/tools/multispec/invoke?params=file:/srv/irods/external/hydroshare/${HS_USR_NAME}/${HS_RES_ID}/data/contents/${HS_FILE_NAME}' cannot be parsed by term_dict {'HS_RES_ID': '2e127085825b4f7fb9525b10b98270de', 'HS_RES_TYPE': 'CompositeResource', 'HS_USR_NAME': 'anonymous', 'HS_AGG_PATH': 'HS_JS_AGG_KEY', 'HS_FILE_PATH': 'HS_JS_FILE_KEY', 'HS_MAIN_FILE': 'HS_JS_MAIN_FILE_KEY'}.
Traceback (most recent call last):
  File "/hydroshare/hs_tools_resource/utils.py", line 37, in parse_app_url_template
    new_url_string = Template(new_url_string).substitute(merged_term_dic)
  File "/usr/local/lib/python3.6/string.py", line 130, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/local/lib/python3.6/string.py", line 123, in convert
    return str(mapping[named])
KeyError: 'HS_FILE_NAME'
```

**Comment by martinseul** [comment]
@sblack-usu is this still an issue?

**Comment by eclark-cuahsi** [comment]
Moved to backlog after meeting on 1.26; additional assessment needed.
