### ISSUE TITLE
Error downloading resource bag

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#4024]
I receive the following error when attempting to download the content of the resource linked below. It's hard to tell what the problem is because the error message is vague. Also, the notification box should not be green, it should be red.

https://www.hydroshare.org/resource/9c4a6e2090924d97955a197fea67fd72/

![image](https://user-images.githubusercontent.com/4822372/97997046-8bb3c580-1db6-11eb-8a54-cd5b2657cbcc.png)

## Suggested fix:
- identify what's causing the error when downloading this resource's bag
- update the error message to be more informative. At the very least add something like: "contact help@cuahsi.org for assistance with this error"
- change the color of the notification box to red instead of green.

**Comment by sblack-usu** [comment]
logs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/billiard/pool.py", line 366, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/usr/local/lib/python3.6/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.6/site-packages/billiard/reduction.py", line 56, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: SessionException(\'SessionException(SessionException(...), "Error processing IRODS request: -1. stderr follows:\\\\n\\\\nb\\\'remote addresses: 152.54.2.121 ERROR: rcExecMyRule error.  status = -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME\\\\\\\\n\\\'")\', "Error processing IRODS request: -1. stderr follows:\\n\\nb\'remote addresses: 152.54.2.121 ERROR: rcExecMyRule error.  status = -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME\\\\n\'")>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'django_irods.icommands.SessionException\'>: it\'s not the same object as django_irods.icommands.SessionException",)''.
```

**Comment by sblack-usu** [comment]
I see over 100 attempts to create this bag.  There are a variety of errors in the logs for different attempts.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/billiard/pool.py", line 366, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/usr/local/lib/python3.6/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.6/site-packages/billiard/reduction.py", line 56, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: SessionException(\'SessionException(SessionException(...), "Error processing IRODS request: 3. stderr follows:\\\\n\\\\nb\\\'remote addresses: 152.54.2.121 ERROR: rmUtil: rm error for /hydroshareZone/home/wwwHydroProxy/9c4a6e2090924d97955a197fea67fd72/bagit.txt, status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION\\\\\\\\n\\\'")\', "Error processing IRODS request: 3. stderr follows:\\n\\nb\'remote addresses: 152.54.2.121 ERROR: rmUtil: rm error for /hydroshareZone/home/wwwHydroProxy/9c4a6e2090924d97955a197fea67fd72/bagit.txt, status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION\\\\n\'")>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'django_irods.icommands.SessionException\'>: it\'s not the same object as django_irods.icommands.SessionException",)''.
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/billiard/pool.py", line 366, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/usr/local/lib/python3.6/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.6/site-packages/billiard/reduction.py", line 56, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: SessionException(\'SessionException(SessionException(...), "Error processing IRODS request: -1. stderr follows:\\\\n\\\\nb\\\'remote addresses: 152.54.2.121 ERROR: rcExecMyRule error.  status = -24000 SYS_INTERNAL_NULL_INPUT_ERR\\\\\\\\n\\\'")\', "Error processing IRODS request: -1. stderr follows:\\n\\nb\'remote addresses: 152.54.2.121 ERROR: rcExecMyRule error.  status = -24000 SYS_INTERNAL_NULL_INPUT_ERR\\\\n\'")>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'django_irods.icommands.SessionException\'>: it\'s not the same object as django_irods.icommands.SessionException",)''.
```

**Comment by Castronova** [comment]
Downloading this bag appears to work now. 

However I'm leaving this ticker open because the error message, specifically the text and the message box color, still needs to be improved.

**Comment by pkdash** [comment]
@Castronova and @dtarb 

> Downloading this bag appears to work now.
> 
> However I'm leaving this ticker open because the error message, specifically the text and the message box color, still needs to be improved.

It seems the error message has been moved to download notification area and a different error message is displayed there. See if this issue can be closed.

**Comment by dtarb** [comment]
Closing on the basis of the above.  I am not able to check this because the bag downloads correctly.
