### ISSUE TITLE
Publication attempt resulting in an error, on a very normal resource. 

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4620]
**Description of the bug**
Resource http://www.hydroshare.org/resource/d2a724a994b34fa3880ca21562912788 is unable to be published. The resource contains 1 rather small file and all needed metadata, but publication attempt results in the following page. 
<img width="425" alt="Screen Shot 2022-05-13 at 11 44 45 AM" src="https://user-images.githubusercontent.com/90924476/168319654-12e5354f-3755-402b-a340-8128133fed7b.png">

Steps to reproduce the bug:
1. Go to ['...'](http://www.hydroshare.org/resource/d2a724a994b34fa3880ca21562912788)
2. Click through the publication steps ( I have attempted it using the admin account and got the same error)
3. you will be redirected to the error page shown above

**Expected behavior**
Should just publish, this resource contains only 1 relatively small spreadsheet. 

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by sblack-usu** [comment]
Logs
```
[12/May/2022 20:17:25] ERROR [django.request:135] Internal Server Error: /hsapi/_internal/57620bc47df1441e8d7aa94991fb39d3/list-referenced-content/
Traceback (most recent call last):
--
[13/May/2022 15:42:19] ERROR [django.request:135] Internal Server Error: /hsapi/_internal/d2a724a994b34fa3880ca21562912788/publish/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/site-packages/gevent/_ssl3.py", line 66, in wrap_socket
    _session=session)
  File "/usr/local/lib/python3.6/site-packages/gevent/_ssl3.py", line 267, in __init__
    raise x
  File "/usr/local/lib/python3.6/site-packages/gevent/_ssl3.py", line 263, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/site-packages/gevent/_ssl3.py", line 587, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='doi.crossref.org', port=443): Max retries exceeded with url: /servlet/deposit (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/hydroshare/hs_core/views/__init__.py", line 908, in publish
    hydroshare.publish_resource(request.user, shortkey)
  File "/hydroshare/hs_core/hydroshare/resource.py", line 1046, in publish_resource
    response = deposit_res_metadata_with_crossref(resource)
  File "/hydroshare/hs_core/hydroshare/resource.py", line 1002, in deposit_res_metadata_with_crossref
    response = requests.post(post_url, data=post_data, files=files)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='doi.crossref.org', port=443): Max retries exceeded with url: /servlet/deposit (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

**Comment by sblack-usu** [comment]
We most likely need to update urllib3.  We are currently on 1.24.3 which was released on May 2, 2019.  The current version is 1.26.9 and released on March 16, 2022
https://pypi.org/project/urllib3/1.24.3/#history

**Comment by sblack-usu** [comment]
A patch to fix this issue has been pushed to production.  Please try publishing the resource again.
