### ISSUE TITLE
Published resource missing published date

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4795]
**Description of the bug**
I happened across a published resource that did not render.  I've included the logs from the error below.  This is caused by a published resource not having a published date.  I ran a query and identified two other resources that fail to render for the same reason.

```
>>> for ra in ResourceAccess.objects.filter(published=True).all():
...     if not ra.resource.metadata.dates.filter(type='published').all().first():
...         print(ra.resource.short_id)
...
d8f59a93f41d4074b61728eb46024713
231886df055e40f2a8186c16753f77f0
cf40bed6ddfe4a94977365105a4ffcec
```

Steps to reproduce the bug:
1. Go to https://hydroshare.org/resource/231886df055e40f2a8186c16753f77f0
2. See error

**Expected behavior**
The resource landing page should render without an error.

**Additional information**
```
[12/Oct/2022 20:08:55] ERROR [django.request:135] Internal Server Error: /resource/231886df055e40f2a8186c16753f77f0/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/hydroshare/hs_core/templatetags/hydroshare_tags.py", line 80, in published_date
    return res_obj.metadata.dates.all().filter(type='published').first().start_date
AttributeError: 'NoneType' object has no attribute 'start_date'
```

**Comment by devincowan** [comment]
plan to update this so that it logs out so we can tell what happened
https://github.com/hydroshare/hydroshare/blob/master/hs_core/views/__init__.py#L925

seems like it failed setting the date here:
https://github.com/hydroshare/hydroshare/blob/master/hs_core/hydroshare/resource.py#L1061

**Comment by devincowan** [comment]
Ran this on Beta, looks like we have some other places where we "log" on the session...we might want to revise these

```
>>> from django.contrib.sessions.models import Session
>>> for s in Session.objects.all():
...     if "validation_error" in s.get_decoded().keys():
...             print(s.get_decoded())
... 
{'hs_tracking_id': 'REDACTED', '_auth_user_id': 'REDACTED', '_auth_user_backend': 'mezzanine.core.auth_backends.MezzanineBackend', '_auth_user_hash': 'REDACTED', 'validation_error': "Failed to create metadata element 'coverage'. ['Value for North latitude must be greater than or equal to that of South latitude.']."}
{'hs_tracking_id': 'REDACTED', '_auth_user_id': 'REDACTED', '_auth_user_backend': 'mezzanine.core.auth_backends.MezzanineBackend', '_auth_user_hash': 'REDACTED', 'validation_error': "Failed to create metadata element 'coverage'. ['Value for North latitude must be greater than or equal to that of South latitude.']."}
```

**Comment by devincowan** [comment]
https://api.crossref.org/v1/works/10.4211/hs.d8f59a93f41d4074b61728eb46024713 (2022-10-05T04:07:36Z)
https://api.crossref.org/v1/works/10.4211/hs.231886df055e40f2a8186c16753f77f0 (2022-10-05T04:06:58Z)
https://api.crossref.org/v1/works/10.4211/hs.cf40bed6ddfe4a94977365105a4ffcec (2022-10-11T19:29:12Z)

Was hoping that these ^^^ Crossreff "created" dates would match the resource "updated" dates:
2022-10-17 14:08:10.654474+00:00
2022-10-17 10:18:36.173396+00:00
2022-10-17 06:21:19.221676+00:00
but no such luck...
It thought it was odd that these resources were updated TODAY, given that they can't really be accessed other than via api.
But then I realized that visiting the resource landing page for them is actually changing the "updated" date #facepalm.

Anyway, I guess we want to manually or via script, update the 3 resources with the Crossref dates, DOIs, and resource_modified.

**Comment by devincowan** [comment]
As a quick fix for the 3 impacted resources (until we can get to the bottom of HOW they got into this state), we could run something like the following:

> import datetime
> from hs_core.models import BaseResource
> from hs_core.hydroshare.resource import get_activated_doi
> from hs_core.hydroshare.util import resource_modified
> 
> res = BaseResource.objects.filter(short_id='d8f59a93f41d4074b61728eb46024713').first()
> pub_date = datetime.datetime.strptime('2022-10-05T04:07:36', '%Y-%m-%dT%H:%M:%S')
> res.metadata.create_element('date', type='published', start_date=pub_date)
> md_args = {'name': 'doi', 'url': get_activated_doi(resource.doi)}
> res.metadata.create_element('Identifier', **md_args)
> utils.resource_modified(res, user, overwrite_bag=False)
> res.save()
> 
> res = BaseResource.objects.filter(short_id='231886df055e40f2a8186c16753f77f0').first()
> pub_date = datetime.datetime.strptime('2022-10-05T04:06:58', '%Y-%m-%dT%H:%M:%S')
> res.metadata.create_element('date', type='published', start_date=pub_date)
> md_args = {'name': 'doi', 'url': get_activated_doi(resource.doi)}
> res.metadata.create_element('Identifier', **md_args)
> utils.resource_modified(res, user, overwrite_bag=False)
> res.save()
> 
> res = BaseResource.objects.filter(short_id='cf40bed6ddfe4a94977365105a4ffcec').first()
> pub_date = datetime.datetime.strptime('2022-10-11T19:29:12', '%Y-%m-%dT%H:%M:%S')
> res.metadata.create_element('date', type='published', start_date=pub_date)
> md_args = {'name': 'doi', 'url': get_activated_doi(resource.doi)}
> res.metadata.create_element('Identifier', **md_args)
> utils.resource_modified(res, user, overwrite_bag=False)
> res.save()

**Comment by devincowan** [comment]
making a reminder that we have to figure out why email was not sent to help@cuahsi.org

**Comment by devincowan** [comment]
I ran the following with empty result on prod:
```
>>> from django.contrib.sessions.models import Session
>>> for s in Session.objects.all():
...     if "validation_error" in s.get_decoded().keys():
...             print(s.get_decoded())
... 
```
so seems we will not be able to the the "logs" for why this occurred. 

But we've improved our email notifications and PR will improve the logging so we can track it down in the future if needed.

**Comment by devincowan** [comment]
So two of the resources resolved last night with the Celery job. But one remains:
https://www.hydroshare.org/resource/d8f59a93f41d4074b61728eb46024713/

When I direct query crossref, here is what I see:
```
<?xml version="1.0" encoding="UTF-8"?>
<doi_batch_diagnostic status="completed" sp="ds5">
   <submission_id>1543730248</submission_id>
   <batch_id>d8f59a93f41d4074b61728eb46024713</batch_id>
   <record_diagnostic status="Failure">
      <doi>10.4211/hs.d8f59a93f41d4074b61728eb46024713</doi>
      <msg>Possible duplicate creation of new DOI</msg>
   </record_diagnostic>
   <batch_data>
      <record_count>1</record_count>
      <success_count>0</success_count>
      <warning_count>0</warning_count>
      <failure_count>1</failure_count>
   </batch_data>
</doi_batch_diagnostic>
```

Failure due to possible duplicate...

**Comment by devincowan** [comment]
reopened because this occurred again for https://www.hydroshare.org/resource/ebd3c73f946344d8adf0431f20576d1c/

See relevant discussion starting with Martin's comment on a different issue:
https://github.com/hydroshare/hydroshare/issues/4878#issuecomment-1344586977

```
$ grep ebd3c73f946344d8adf0431f20576d1c django.log
[28/Nov/2022 17:28:24] ERROR [django.request:230] Forbidden (Permission denied): /hsapi/_internal/ebd3c73f946344d8adf0431f20576d1c/publish/
[28/Nov/2022 17:28:24] ERROR [django.request:230] Internal Server Error: /hsapi/_internal/ebd3c73f946344d8adf0431f20576d1c/publish/
[28/Nov/2022 17:28:28] ERROR [django.request:230] Forbidden (Permission denied): /hsapi/_internal/ebd3c73f946344d8adf0431f20576d1c/publish/

$ grep ebd3c73f946344d8adf0431f20576d1c hydroshare.log
[28/Nov/2022 17:24:58] INFO [root:265] Generic aggregation was created for file:ebd3c73f946344d8adf0431f20576d1c/data/contents/Supporting_Information_SI_-_2022WR032866.pdf.
```

https://api.crossref.org/v1/works/10.4211/hs.ebd3c73f946344d8adf0431f20576d1c
Crossref looks all okay

**Comment by devincowan** [comment]
I "healed" this particular resource so that the user could access for now (by setting the published date, which was missing).

**Comment by devincowan** [comment]
As previous work on this issue, we introduced some better logging in PR [#4800](https://github.com/hydroshare/hydroshare/pull/4800). I looked for ValidationErrors in the logs but the ones I found didn't seem relevant.

Also searched for session errors (same as https://github.com/hydroshare/hydroshare/issues/4795#issuecomment-1282645532) but none were found.

**Comment by pkdash** [comment]
@devincowan Locally you can test this. Create a resource. Create any aggregation. May be a single file aggregation. Publish this resource. Then see if you can remove the aggregation (content type) from that file from which you created the aggregation. I was able to remove aggregation from a published resource when I was testing your PR.

**Comment by devincowan** [comment]
Thanks @pkdash I get it now!
Sad to say that I don't think this is how we keep getting published resources without a pub date. But not that I understand what you're getting at (content modifiable during HIL metadata review), I did create https://github.com/hydroshare/hydroshare/pull/4895 to resolve that

**Comment by devincowan** [comment]
Closing this for now, as we are changing our publication workflow with 2.1 release.
If this issue comes up again, we hope to catch it closer to when it occurs.

**Comment by devincowan** [comment]
We saw this again today for resource:
https://hydroshare.org/resource/fa1eb51c8756427d9fc50c415b714557/
```python
>>> from hs_core.models import BaseResource
>>> r =BaseResource.objects.get(short_id='fa1eb51c8756427d9fc50c415b714557')
>>> r
<BaseResource: Impacts of Urbanization on the Riverine Flooding in Major Cities Across the Eastern United States>
>>> r.metadata.dates.all().filter(type='published')
<QuerySet []>
>>> r.metadata.dates.all()
<QuerySet [<Date: created 2024-05-30 22:03:50.568708+00:00>, <Date: modified 2024-12-17 11:01:31.257072+00:00>, <Date: reviewStarted 2024-12-17 04:56:55.364163+00:00>]>
>>> r.raccess.review_pending
False
>>> r.raccess.published
True
```

it was set as published but it didn't have a "Publisher" which makes me think it failed here:
https://github.com/hydroshare/hydroshare/blob/2.15.9.1/hs_core/hydroshare/resource.py#L1160

We improved logging in
https://github.com/hydroshare/hydroshare/pull/4800
but I'm not seeing anything in logs that helps me to understand how this got "published" without a publication date

**Comment by martinseul** [comment]
@sblack-usu can this be closed seems stale by now?
