### ISSUE TITLE
celery job failing: unzip_task

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4932]
**Description of the bug**
[unzip_task](https://github.com/hydroshare/hydroshare/blob/2.1/hs_core/tasks.py#L784) celery task started failing after [2.1 release](https://github.com/hydroshare/hydroshare/issues/4832)

![image](https://user-images.githubusercontent.com/17934193/210798942-613eddf6-a6ac-4141-bedc-7aed58e84f18.png)
Related to https://github.com/hydroshare/hydroshare/issues/2538

Steps to reproduce the bug:
http://www1-hydroshare.edc.renci.org:5555/api/tasks?state=FAILURE&limit=500&taskname=hs_core.tasks.unzip_task

**Expected behavior**
We should make sure that we are handling the exception properly

**Additional information**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/hydroshare/hs_core/tasks.py", line 789, in unzip_task
    unzip_to_folder)
  File "/hydroshare/hs_core/views/utils.py", line 1139, in unzip_file
    raise SuspiciousFileOperation(err_msg)
django.core.exceptions.SuspiciousFileOperation: Zip file has file with name that contains one or more prohibited characters.
```

**Comment by devincowan** [comment]
related to https://github.com/hydroshare/hydroshare/issues/4888

**Comment by devincowan** [comment]
This is expected behavior.
