### ISSUE TITLE
Geoserver update_web_services task should parse result

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4954]
**Description of the bug**
`update_web_services` Celery task was failing before [rc-2.3](https://github.com/hydroshare/hydroshare/tree/rc-2.3), [checklist](https://github.com/hydroshare/hydroshare/issues/4936)

Failures were effectively ignored by work in issue https://github.com/hydroshare/hydroshare/issues/4630, PR: https://github.com/hydroshare/hydroshare/pull/4939
Once [this issue](https://github.com/hydroshare/hs_data_services/issues) is resolved with the hs_data_services middleware, the Hydroshare task should once again parse the response from the middleware.

### More info
This function sends a resource id to the HydroShare web services manager
    application. Seems there is a key error and the Geoserver is not returning a json response

Steps to reproduce the bug:
Navigate to the celery worker task UI on production and search for the update_web_services task.

**Expected behavior**
Celery task should finish correctly. Geoserver should return a json serializable response.

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/tasks.py#L751

Example log snippet:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'KeyError' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 449, in trace_task
    uuid, retval, task_request, publish_result,
  File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 149, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/amqp.py", line 140, in store_result
    delivery_mode=self.delivery_mode,
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 70, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
kombu.exceptions.EncodeError: Object of type 'KeyError' is not JSON serializable
```

**Comment by devincowan** [comment]
@martinseul FYI I have a [branch on hs_data_services](https://github.com/hydroshare/hs_data_services/tree/local-dev-dont-merge) that runs simply for me locally alongside hydroshare and geoserver.

**Comment by devincowan** [comment]
I noticed that `hs_core.tasks.update_web_services` ([Celery task](https://github.com/hydroshare/hydroshare/blob/2.7.1/hs_core/tasks.py#L776)) has been failing since ~8/18/2023.
