### ISSUE TITLE
json endpoints broken for resources in publishing review

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#5012]
**Description of the bug**
The `hsapi2/resource/{id}/json/` endpoint (and other places that use hsmodels) are currently broken due to a new date type (review_started) that is not a supported enumeration of http://purl.org/dc/terms/.

Steps to reproduce the bug:
1. Go to https://hydroshare.org/hsapi2
2. Send a GET request for a resource in review (31b56632213345db889a9eee981619f6)
3. See error

**Expected behavior**

**Additional information**
The quick fix is probably to update the rdf_triples method in the Date AbstractMetaDataElement implementation to not create a triple for dates with the new type. 
```
[17/Mar/2023 02:10:12] ERROR [django.request:224] Internal Server Error: /hsapi2/resource/31b56632213345db889a9eee981619f6/json/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/hydroshare/hs_rest_api2/views/metadata.py", line 28, in resource_metadata_json
    md_json = resource_metadata_json_loads(resource)
  File "/hydroshare/hs_rest_api2/metadata.py", line 73, in resource_metadata_json_loads
    return json.loads(resource_metadata(resource).json())
  File "/hydroshare/hs_rest_api2/metadata.py", line 66, in resource_metadata
    return load_metadata_from_file(istorage, file_with_path)
  File "/hydroshare/hs_rest_api2/metadata.py", line 47, in load_metadata_from_file
    metadata = load_rdf(f.read())
  File "/usr/local/lib/python3.9/site-packages/hsmodels/schemas/__init__.py", line 71, in load_rdf
    rdf_metadata = _parse(schema, g)
  File "/usr/local/lib/python3.9/site-packages/hsmodels/schemas/__init__.py", line 181, in _parse
    parsed_class = _parse(clazz, metadata_graph, value)
  File "/usr/local/lib/python3.9/site-packages/hsmodels/schemas/__init__.py", line 199, in _parse
    instance = schema(**kwargs, rdf_subject=subject)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DateInRDF
type
  value is not a valid enumeration member; permitted: 'http://purl.org/dc/terms/modified', 'http://purl.org/dc/terms/created', 'http://purl.org/dc/terms/valid', 'http://purl.org/dc/terms/available', 'http://purl.org/dc/terms/published' (type=type_error.enum; enum_values=[<DateType.modified: 'http://purl.org/dc/terms/modified'>, <DateType.created: 'http://purl.org/dc/terms/created'>, <DateType.valid: 'http://purl.org/dc/terms/valid'>, <DateType.available: 'http://purl.org/dc/terms/available'>, <DateType.published: 'http://purl.org/dc/terms/published'>])
```

**Comment by devincowan** [comment]
I verified that the following change on hsmodels "patches" the hsapi2 endpoint:
https://github.com/hydroshare/hsmodels/compare/main...rdf_test

Of course, we should ideally handle the "published" and the "review_pending" terms differently (instead of falsely implying that they are DCTERMS when they aren't). I guess we should add these to HSTERMS? Or what do you recommend @sblack-usu ? 

I will open a PR on hsmodels for the above patch, if that's the approach you'd like for the time being...

**Comment by devincowan** [comment]
release of PR https://github.com/hydroshare/hydroshare/pull/5020 will depend on:
https://github.com/hydroshare/hs_docker_base/pull/84
and 
https://github.com/hydroshare/hsmodels/pull/41

**Comment by devincowan** [comment]
@martinseul I know you said 2.6 for this issue, but I added it to 2.5 because 2.5 is delayed and this is a bug with a fix that is ready
