### ISSUE TITLE
create_temp_zip celery task fails: downloading raster aggregation that is nested in a folder whose name has a space

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5013]
**Description of the bug**
Looks like someone has been working with this resource
https://www.hydroshare.org/resource/4b517deaa07243aa8c46a58646dd4281/
possibly attempting to zip up some of the files.

The temp_zip task
https://github.com/hydroshare/hydroshare/blob/2.4/hs_core/tasks.py#L437
is failing with the following:
```
<MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: SessionException(\\'SessionException(SessionException(...), "Error processing IRODS request: 3. stderr follows:\\\\\\\\n\\\\\\\\nb\\\\\\'remote addresses: 152.54.2.121 ERROR: resolveRodsTarget: srcPath /hydroshareZone/home/wwwHydroProxy/4b517deaa07243aa8c46a58646dd4281/data/contents/Catchments%20DEM/DEM_QUI3.vrt does not exist\\\\\\\\\\\\\\\\nremote addresses: 152.54.2.121 ERROR: cpUtil: resolveRodsTarget error, status = -317000 status = -317000 USER_INPUT_PATH_ERR\\\\\\\\\\\\\\\\n\\\\\\'")\\', "Error processing IRODS request: 3. stderr follows:\\\\n\\\\nb\\'remote addresses: 152.54.2.121 ERROR: resolveRodsTarget: srcPath /hydroshareZone/home/wwwHydroProxy/4b517deaa07243aa8c46a58646dd4281/data/contents/Catchments%20DEM/DEM_QUI3.vrt does not exist\\\\\\\\nremote addresses: 152.54.2.121 ERROR: cpUtil: resolveRodsTarget error, status = -317000 status = -317000 USER_INPUT_PATH_ERR\\\\\\\\n\\'")>, None)''. Reason: ''PicklingError("Can\\'t pickle <class \\'django_irods.icommands.SessionException\\'>: it\\'s not the same object as django_irods.icommands.SessionException")''.>
```

Steps to reproduce the bug:
I haven't been able to reproduce this yet...

**UPDATE** Pabitra reproduced. The issue was a space in folder name...

**Expected behavior**
Download without error

**Additional information**
HS v2.4

**Comment by devincowan** [comment]
@pkdash here is the issue that we noticed today

**Comment by devincowan** [comment]
@pkdash was able to reproduce: the issue is downloading a raster aggregation that is inside a folder whose name has a space

**Comment by devincowan** [comment]
@pkdash I saw a similar error in Celery log today:

> Traceback (most recent call last):   File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 366, in workloop     put((READY, (job, i, result, inqW_fd)))   File "/usr/local/lib/python3.9/site-packages/billiard/queues.py", line 366, in put     self.send_payload(ForkingPickler.dumps(obj))   File "/usr/local/lib/python3.9/site-packages/billiard/reduction.py", line 56, in dumps     cls(buf, protocol).dump(obj) billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: SessionException(\'SessionException(SessionException(...), "Error processing IRODS request: 3. stderr follows:\\\\n\\\\nb\\\'remote addresses: 152.54.2.121 ERROR: bunUtil: opr error for /hydroshareZone/home/wwwHydroProxy/zips/2023-04-06/cc268bf6bc5845c5bab51018f7e00886/0a596929a3e5411bb0032a8de35e5089/data/contents/RouteLink_CONUS.nc, status = -77000 status = -77000 SYS_COPY_NOT_EXIST_IN_RESC\\\\\\\\n\\\'")\', "Error processing IRODS request: 3. stderr follows:\\n\\nb\'remote addresses: 152.54.2.121 ERROR: bunUtil: opr error for /hydroshareZone/home/wwwHydroProxy/zips/2023-04-06/cc268bf6bc5845c5bab51018f7e00886/0a596929a3e5411bb0032a8de35e5089/data/contents/RouteLink_CONUS.nc, status = -77000 status = -77000 SYS_COPY_NOT_EXIST_IN_RESC\\\\n\'")>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'django_irods.icommands.SessionException\'>: it\'s not the same object as django_irods.icommands.SessionException")''.

Looks like this was for the following resource which is @aaraney 's:
https://www.hydroshare.org/resource/0a596929a3e5411bb0032a8de35e5089/
Doesn't look like there is a space in the aggregation name anymore, but maybe there was at one time...

Maybe something for us to check after 2.5 release

**Comment by devincowan** [comment]
@pkdash adding another resource that appears to have this issue.
Think these resources could be good to verify on production after our 2.5 release
https://www.hydroshare.org/resource/fc621d75985c4695b6758ade312241c6/

**Comment by devincowan** [comment]
Create temp zip also fails for:
https://www.hydroshare.org/resource/2dbd6e849a754c0981b99ee7c09031eb/
with
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 366, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/usr/local/lib/python3.9/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.9/site-packages/billiard/reduction.py", line 56, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: SessionException(\'SessionException(SessionException(...), "Error processing IRODS request: 3. stderr follows:\\\\n\\\\nb\\\'remote addresses: 152.54.2.121 ERROR: putUtil: put error for /hydroshareZone/home/wwwHydroProxy/2dbd6e849a754c0981b99ee7c09031eb/data/contents/netcdf/max_snow_depth_CTRL_meta.xml, status = -1803000 status = -1803000 HIERARCHY_ERROR\\\\\\\\n\\\'")\', "Error processing IRODS request: 3. stderr follows:\\n\\nb\'remote addresses: 152.54.2.121 ERROR: putUtil: put error for /hydroshareZone/home/wwwHydroProxy/2dbd6e849a754c0981b99ee7c09031eb/data/contents/netcdf/max_snow_depth_CTRL_meta.xml, status = -1803000 status = -1803000 HIERARCHY_ERROR\\\\n\'")>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'django_irods.icommands.SessionException\'>: it\'s not the same object as django_irods.icommands.SessionException")''.
```
as of HS 2.4.2
