### ISSUE TITLE
create_temp_zip fails due to ResourceFile duplicate

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5044]
**Description of the bug**
Attempting to create a bagit zip for the following resource never completes
https://www.hydroshare.org/resource/2a74d5357582420b9aaf0e2bf8f79f93/
![image](https://user-images.githubusercontent.com/17934193/232772797-a37935c1-20b0-491c-b722-539411a09fbe.png)

The celery worker shows:
```Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/hydroshare/hs_core/tasks.py", line 458, in create_temp_zip
    res.create_aggregation_meta_files(path=short_path)
  File "/hydroshare/hs_composite_resource/models.py", line 294, in create_aggregation_meta_files
    aggregation = self.get_aggregation_by_name(path)
  File "/hydroshare/hs_composite_resource/models.py", line 333, in get_aggregation_by_name
    res_file = ResourceFile.get(self, file=base, folder=folder)
  File "/hydroshare/hs_core/models.py", line 3409, in get
    return ResourceFile.objects.get(object_id=resource.id,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
hs_core.models.ResourceFile.MultipleObjectsReturned: get() returned more than one ResourceFile -- it returned 2!
```

**Expected behavior**
A meaningful error should be returned in the UI, or the zip should succeed.

**Additional information**
Related to #5013 
HS version 2.4.2

**Comment by devincowan** [comment]
Related to https://github.com/hydroshare/hydroshare/issues/4432
