### ISSUE TITLE
preventative measures for bag generation process

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5110]
**Describe the feature you'd like and what it will do**
Add a max size limit on bag generation. And the bag generation code must clean up after itself. Maybe also a daily sweep of cleaning out tmp or a job periodically watching the size of tmp and cleaning up more frequently.

**Why is this feature important?**
We have been experiencing stalled celery processes and bagit creation failure on prod, believed due to requests to zip large files.

Example: 100GB .csv here
https://www.hydroshare.org/resource/84d1b8b60f274ba4be155881129561a9/

**Additional context**
HS 2.6.1

**Comment by devincowan** [comment]
`[hydro-service@www2-hydroshare hydroshare]$ docker logs defaultworker`
```

[2023-06-29 15:45:12,986: ERROR/ForkPoolWorker-5] Failed to add documents to Solr: Failed to connect to server at http://localhost:8983/solr/collection1/update/?commit=true: HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/collection1/update/?commit=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3cb15c6b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3cb15c6b20>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/collection1/update/?commit=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3cb15c6b20>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pysolr.py", line 416, in _send_request
    resp = requests_method(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/collection1/update/?commit=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3cb15c6b20>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/haystack/backends/solr_backend.py", line 99, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/usr/local/lib/python3.9/site-packages/pysolr.py", line 1042, in add
    return self._update(
  File "/usr/local/lib/python3.9/site-packages/pysolr.py", line 564, in _update
    return self._send_request(
  File "/usr/local/lib/python3.9/site-packages/pysolr.py", line 431, in _send_request
    raise SolrError(error_message % (url, err))
pysolr.SolrError: Failed to connect to server at http://localhost:8983/solr/collection1/update/?commit=true: HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/collection1/update/?commit=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3cb15c6b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
