### ISSUE TITLE
Delete resource task fails due to duplicate key violation

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5279]
**Description of the bug**
Attempts deleting the following resources fail
https://www.hydroshare.org/resource/36a61f93ede241a09ce5ae786569e772/
https://www.hydroshare.org/resource/318451ad89ed4f53bdb769a2a8ba771c/
https://www.hydroshare.org/resource/78d734aa984c44898d0192cf828afb75/
https://www.hydroshare.org/resource/f29b431aac804b5a9b8c68921a2d6391/

with following exception:
```
 	IntegrityError('duplicate key value violates unique constraint "hs_core_resourcefile_resource_file_ab307f6e_uniq"\nDETAIL: Key (resource_file)=() already exists.\n') 
```
http://www1-hydroshare.edc.renci.org:5555/task/5ad36a93-f553-4cc9-9ddf-205d5487b87a
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "hs_core_resourcefile_resource_file_ab307f6e_uniq"
DETAIL:  Key (resource_file)=() already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/hydroshare/hs_core/tasks.py", line 928, in delete_resource_task
    res.delete()
  File "/usr/local/lib/python3.9/site-packages/mezzanine/core/models.py", line 498, in delete
    super().delete(*args, **kwargs)
  File "/hydroshare/hs_core/models.py", line 2472, in delete
    fl.delete(delete_logical_file=True)
  File "/hydroshare/hs_core/models.py", line 3136, in delete
    self.resource_file.delete()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 114, in delete
    self.instance.save()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "hs_core_resourcefile_resource_file_ab307f6e_uniq"
DETAIL:  Key (resource_file)=() already exists.
```

**Additional information**
HS v2.11

**Comment by devincowan** [comment]
@kjlippold is there anything unique about these resources? Looks like you were testing archiving?

**Comment by danames** [comment]
I can't see those resources. When were they created? If they were part of @kjlippold 's research during his time at BYU they can probably be removed as part of his testing/experimenting with the middleware.

**Comment by devincowan** [comment]
@danames thanks, looks like @kjlippold created all of these last week ~ Dec 1, 2023

**Comment by devincowan** [comment]
closing for now, I haven't been able to replicate this.
@kjlippold if you run into issues, please let us know and reopen
