### ISSUE TITLE
Error when HIL approving metadata review

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5400]
**Description of the bug**
When @ClaraCogswell approved metadata review for this resource requesting publication:
https://www.hydroshare.org/resource/436be40748a246269102b20211b49762

Hydroshare shows a general error page indicating that there was a backend error.

My hunch is that there is something wrong with this Enum:
```
>>> from hs_core.models import BaseResource
>>> r = BaseResource.objects.get(short_id="436be40748a246269102b20211b49762")
>>> r.get_crossref_deposit_xml()
[...]
(it works)
>>> r
<BaseResource: Dataset for "Technical Note: Preventing CO2 overestimation from mercuric or copper (II) chloride preservation of dissolved greenhouse gases in freshwater samples" Clayer et al.>
>>> r.metadata.dates.all().filter(type='reviewStarted').first()
<Date: reviewStarted 2024-03-04 15:03:15.663429+00:00>
>>> r.can_be_submitted_for_metadata_review
True
>>> from hs_core.hydroshare.resource import get_resource_doi
>>> get_resource_doi(r.short_id, 'pending')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/hydroshare/hs_core/hydroshare/resource.py", line 967, in get_resource_doi
    if flag not in CrossRefSubmissionStatus:
  File "/usr/local/lib/python3.9/enum.py", line 397, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'str' and 'EnumMeta'
```

https://github.com/hydroshare/hydroshare/blob/2.13.2/hs_core/views/__init__.py#L2111

HS v2.13.2

**Comment by devincowan** [comment]
My hunch was that there was something wrong fetching the DOI:
>>> from hs_core.hydroshare.resource import get_resource_doi
>>> get_resource_doi(r.short_id, 'pending')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/hydroshare/hs_core/hydroshare/resource.py", line 967, in get_resource_doi
    if flag not in CrossRefSubmissionStatus:
  File "/usr/local/lib/python3.9/enum.py", line 397, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'str' and 'EnumMeta'
```
1. [metadata_review](https://github.com/hydroshare/hydroshare/blob/2.13.2/hs_core/views/__init__.py#L2111) calls
2. [get_resource_doi](https://github.com/hydroshare/hydroshare/blob/2.13.2/hs_core/hydroshare/resource.py#L1125)
3. which looks like it fails with a TypeError between str and enum

But that was just because I should've called `get_resource_doi(pk, CrossRefSubmissionStatus.FAILURE)` so I'm back to searching for the source of this problem.

**Comment by devincowan** [comment]
Ah here is the log line:
```
[04/Mar/2024 15:32:34] ERROR [django.request:224] Internal Server Error: /hsapi/_internal/metadata_review/436be40748a246269102b20211b49762/approve/1/c3ddtg-d74b01548b0970f78f55341685c8ed0a/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/hydroshare/hs_core/views/__init__.py", line 2141, in metadata_review
    hydroshare.publish_resource(user, shortkey)
  File "/hydroshare/hs_core/hydroshare/resource.py", line 1110, in publish_resource
    raise ValidationError("Resource can only be published by an admin user")
django.core.exceptions.ValidationError: ['Resource can only be published by an admin user']
```

**Comment by devincowan** [comment]
We should evaluate how we [alter_review_pending_flags](https://github.com/hydroshare/hydroshare/blob/2.13.3/hs_core/views/__init__.py#L2139). We have a problem: the flags are being updated before the `publish_resource` call, but then the publish fails (due to auth) and the review flags are never reset. This means that a failed publication attempt can take the resource out of metadata review

**Comment by devincowan** [comment]
List of impacted resources
https://www.hydroshare.org/resource/45930399530b42c391e642f3c5202a8d/
https://www.hydroshare.org/resource/727e01d85a08419aaa3a8dee2856f005/
https://www.hydroshare.org/resource/5035e8eff7284881bf61128553b64d47/
https://www.hydroshare.org/resource/774abdf009a54b358d35e501eca34fd8/

**Comment by devincowan** [comment]
Verified that the issue occurs when the approving admin is logged into HydroShare using an account that is not an admin.
They click the link to approve/deny the publication request.
The ValidationError occurs because the publication request is made using the logged in account instead of the `uidb36` in the request param
