### ISSUE TITLE
Folder zip fails with CAT_UNKNOWN_COLLECTION

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5451]
**Description of the bug**
[create_temp_zip](https://github.com/hydroshare/hydroshare/blob/2.13.6/hs_core/tasks.py#L749) fails when calling `istorage.zipup`

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 366, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/usr/local/lib/python3.9/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.9/site-packages/billiard/reduction.py", line 56, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: SessionException(\'SessionException(SessionException(...), "Error processing IRODS request: 3. stderr follows:\\\\n\\\\nb\\\'remote addresses: 152.54.2.121 ERROR: bunUtil: opr error for /hydroshareZone/home/wwwHydroProxy/8b02895f02c14dd1a749bcc5584a5c55/data/contents/Metadata, status = -814000 status = -814000 CAT_UNKNOWN_COLLECTION\\\\\\\\n\\\'")\', "Error processing IRODS request: 3. stderr follows:\\n\\nb\'remote addresses: 152.54.2.121 ERROR: bunUtil: opr error for /hydroshareZone/home/wwwHydroProxy/8b02895f02c14dd1a749bcc5584a5c55/data/contents/Metadata, status = -814000 status = -814000 CAT_UNKNOWN_COLLECTION\\\\n\'")>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'django_irods.icommands.SessionException\'>: it\'s not the same object as django_irods.icommands.SessionException")''.
```

Steps to reproduce the bug:
1. Go to https://www.hydroshare.org/resource/8b02895f02c14dd1a749bcc5584a5c55/
2. Attempt to `download zipped` for the "Metadata" directory in the resource

**Expected behavior**
No error when downloading zipped dir.

**Additional information**
HS v 2.13.6

**Comment by devincowan** [comment]
hmm issue seems to have resolved itself (at least for this resource)...
