### ISSUE TITLE
quota emails task failure

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5518]
```sh
Failure detected for task hs_core.tasks.send_over_quota_emails. Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 54, in run
    ret = task.retry(exc=exc, **retry_kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 717, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "/hydroshare/hs_core/tasks.py", line 522, in send_over_quota_emails
    update_quota_usage(u.username, notify_user=False)
  File "/hydroshare/hs_core/hydroshare/resource.py", line 146, in update_quota_usage
    uz = get_user_zone_usage(username)
  File "/hydroshare/hs_core/hydroshare/resource.py", line 111, in get_user_zone_usage
    uqUserZoneSize = istorage.getAVU(uz_bagit_path, attname)
  File "/hydroshare/django_irods/storage.py", line 224, in getAVU
    vals = stdout[2].split(":")
IndexError: list index out of range
```

**Comment by devincowan** [comment]
Likely resolve in https://github.com/hydroshare/hydroshare/pull/5526 as a byproduct of removing the Userzone AVUs
