### ISSUE TITLE
DB unresponsive due to "too many clients"

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5558]
```sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 153, in handle_uncaught_exception
    return callback(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mezzanine/core/views.py", line 210, in server_error
    return HttpResponseServerError(t.render(context, request))
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/mezzanine/template/__init__.py", line 52, in render
    context[parts[-1]] = tag_func(*args, **kwargs)
  File "/hydroshare/theme/templatetags/theme_tags.py", line 15, in get_site_conf
    return SiteConfiguration.objects.get_or_create(site_id=current_site_id())[0]
  File "/usr/local/lib/python3.9/site-packages/mezzanine/utils/sites.py", line 43, in current_site_id
    site_id = request.session.get("site_id", None)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 80, in get
    return self._session.get(key, default)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "postgis" (34.118.230.224), port 5432 failed: FATAL:  sorry, too many clients already
```
https://hydroshare.slack.com/archives/C0770HALMJQ/p1721416498209229

**Comment by devincowan** [comment]
related to https://github.com/hydroshare/hydroshare/issues/5159

**Comment by sblack-usu** [comment]
I deleted 20 resources without any issues. I don't think it is resource delete that caused the issue. Only 4 deletes would occur at a time anyways, since the deletes are async. It may have more to do with the number of files or some other database operations associated with a particular resource...

**Comment by devincowan** [comment]
Thanks for testing!
Possible that there were some large files in the resources, but none of them should have had more than 1 or two files.
And very little metadata associated. No aggregations in any of the resources...

**Comment by sblack-usu** [comment]
Sounds like there was another factor involved here

**Comment by devincowan** [comment]
I'm going to close this for now. I know there was a large stack of resource tasks in the worker's queue and possibly that was more the culprit than the bulk delete

**Comment by devincowan** [comment]
re-opening
https://hydroshare.slack.com/archives/C0770HALMJQ/p1723220837665989

**Comment by devincowan** [comment]
```
postgres=#
postgres=# show max_connections;
 max_connections
-----------------
 100
(1 row)
```

**Comment by cbcunc** [comment]
max_connections of 100 must be a limitation in the image. The default config for PG is 1000.

**Comment by devincowan** [comment]
Thanks @cbcunc I agree that we don't want to mess with the max_connections setting in PG.
Docs say the default is 100
https://www.postgresql.org/docs/current/runtime-config-connection.html#GUC-MAX-CONNECTIONS

**Comment by devincowan** [comment]
reopened https://hydroshare.slack.com/archives/C79R38HBQ/p1727888556498659

**Comment by devincowan** [comment]
closing for now along with https://github.com/hydroshare/hydroshare/issues/5047 and deployment of https://github.com/CUAHSI/platform-recipes/pull/71
