### ISSUE TITLE
Nightly async tasks fail with 

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5602]
Several notifications every night for two different jobs:
`nightly_cache_file_system_metadata` and `hs_core.tasks.nightly_repair_resource_files`

The notifications come from "hydroshare" email but I have a suspicion that these are actually from our beta cluster.

```sh
Failure detected for task hs_core.tasks.nightly_cache_file_system_metadata. Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 1: ...              FROM "auth_user" WHERE "auth_user"."id" = None
                                                                   ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 54, in run
    ret = task.retry(exc=exc, **retry_kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 717, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "/hydroshare/hs_core/tasks.py", line 1176, in nightly_cache_file_system_metadata
    set_res_files_system_metadata(res)
  File "/hydroshare/hs_core/tasks.py", line 1156, in set_res_files_system_metadata
    res_file.set_system_metadata(resource=resource, save=False)
  File "/hydroshare/hs_core/models.py", line 3300, in set_system_metadata
    self.calculate_size(resource=resource, save=save)
  File "/hydroshare/hs_core/models.py", line 3286, in calculate_size
    self._size = self.resource_file.size
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 71, in size
    return self.storage.size(self.name)
  File "/hydroshare/django_irods/s3_backend.py", line 173, in size
    bucket, name = bucket_and_name(name)
  File "/hydroshare/django_irods/utils.py", line 31, in bucket_and_name
    cursor.execute(owner_username_query)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column "none" does not exist
LINE 1: ...              FROM "auth_user" WHERE "auth_user"."id" = None
```

**Comment by sblack-usu** [comment]
FYI, you can parameterize any value in the settings yaml with a value from the environment values files like this. https://github.com/CUAHSI/platform-recipes/blob/main/hydroshare/chart/templates/settings.yaml#L953

I suspect there are several config values that need to be environment specific that currently are not.

**Comment by devincowan** [comment]
Thanks Scott, very helpful and yes I suspect the same
