### ISSUE TITLE
celery queue hangs with missing args for geoconnex job

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5640]
```
Failure detected for task hs_core.tasks.update_from_geoconnex_task. Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.9/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 325, in on_result_readable
    next(it)
  File "/usr/local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 306, in _recv_message
    message = load(bufv)
TypeError: __init__() missing 1 required positional argument: 'type_'
```

**Comment by devincowan** [comment]
I haven't been able to preproduce so closing for now
