### ISSUE TITLE
Fix error with REST tests on develop

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#698]
Under CI, the following error is occurring:

    ERROR: test_create_get_delete_resource (test_live.TestGetResourceList)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/hydrobuild/hydroshare/sampledata/tests/api/test_live.py", line 232, in test_create_get_delete_resource
        stream = hs.getResource(newres)
      File "/home/hydrobuild/hydroshare/env/lib/python2.7/site-packages/hs_restclient/__init__.py", line 356, in getResource
        stream = self._getBagStream(pid)
      File "/home/hydrobuild/hydroshare/env/lib/python2.7/site-packages/hs_restclient/__init__.py", line 396, in _getBagStream
        r = self._request('GET', bag_url, stream=True)
      File "/home/hydrobuild/hydroshare/env/lib/python2.7/site-packages/hs_restclient/__init__.py", line 174, in _request
        r = self.session.request(method, url, params=params, data=data, files=files, headers=headers, stream=stream)
      File "/home/hydrobuild/hydroshare/env/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/hydrobuild/hydroshare/env/lib/python2.7/site-packages/requests/sessions.py", line 597, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "/home/hydrobuild/hydroshare/env/lib/python2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
        **adapter_kwargs
      File "/home/hydrobuild/hydroshare/env/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
        r = adapter.send(request, **kwargs)
      File "/home/hydrobuild/hydroshare/env/lib/python2.7/site-packages/requests/adapters.py", line 412, in send
        raise ConnectionError(err, request=request)
    ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by hyi** [comment]
@jbradberry Not sure whether this is still an issue, but since you are taking on REST API, I am putting this issue on your plate for now.

**Comment by mjstealey** [comment]
close
